//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18444
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NVRLogin.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NVRLogin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap applicationMenuIcon {
            get {
                object obj = ResourceManager.GetObject("applicationMenuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap bandwidthMenuIcon {
            get {
                object obj = ResourceManager.GetObject("bandwidthMenuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/controllerBG.png 的當地語系化字串。
        /// </summary>
        internal static string BGControllerBG {
            get {
                return ResourceManager.GetString("BGControllerBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/loginPanel.png 的當地語系化字串。
        /// </summary>
        internal static string BGLoginPanel {
            get {
                return ResourceManager.GetString("BGLoginPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/loginPanel2.png 的當地語系化字串。
        /// </summary>
        internal static string BGLoginPanel2 {
            get {
                return ResourceManager.GetString("BGLoginPanel2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap bitrateIcon {
            get {
                object obj = ResourceManager.GetObject("bitrateIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap cancelButotn {
            get {
                object obj = ResourceManager.GetObject("cancelButotn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap controllerBG {
            get {
                object obj = ResourceManager.GetObject("controllerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap cpuIcon {
            get {
                object obj = ResourceManager.GetObject("cpuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap forgetMe {
            get {
                object obj = ResourceManager.GetObject("forgetMe", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap fullscreen {
            get {
                object obj = ResourceManager.GetObject("fullscreen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap fullscreenMenuIcon {
            get {
                object obj = ResourceManager.GetObject("fullscreenMenuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap functionBg {
            get {
                object obj = ResourceManager.GetObject("functionBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap headerBg {
            get {
                object obj = ResourceManager.GetObject("headerBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/bitrateIcon.png 的當地語系化字串。
        /// </summary>
        internal static string IMGBitrateIcon {
            get {
                return ResourceManager.GetString("IMGBitrateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/cancelButotn.png 的當地語系化字串。
        /// </summary>
        internal static string IMGCancelButotn {
            get {
                return ResourceManager.GetString("IMGCancelButotn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/collapse.png 的當地語系化字串。
        /// </summary>
        internal static string IMGCollapse {
            get {
                return ResourceManager.GetString("IMGCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/cpuIcon.png 的當地語系化字串。
        /// </summary>
        internal static string IMGCPUIcon {
            get {
                return ResourceManager.GetString("IMGCPUIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/expand.png 的當地語系化字串。
        /// </summary>
        internal static string IMGExpand {
            get {
                return ResourceManager.GetString("IMGExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/forgetMe.png 的當地語系化字串。
        /// </summary>
        internal static string IMGForgetMe {
            get {
                return ResourceManager.GetString("IMGForgetMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/FullScreen.png 的當地語系化字串。
        /// </summary>
        internal static string IMGFullScreen {
            get {
                return ResourceManager.GetString("IMGFullScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/functionBg.png 的當地語系化字串。
        /// </summary>
        internal static string IMGFunctionBg {
            get {
                return ResourceManager.GetString("IMGFunctionBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/headerBg.png 的當地語系化字串。
        /// </summary>
        internal static string IMGHeaderBg {
            get {
                return ResourceManager.GetString("IMGHeaderBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/loadingClock.png 的當地語系化字串。
        /// </summary>
        internal static string IMGLoadingClock {
            get {
                return ResourceManager.GetString("IMGLoadingClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/loginButton.png 的當地語系化字串。
        /// </summary>
        internal static string IMGLoginButton {
            get {
                return ResourceManager.GetString("IMGLoginButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/menuBg.png 的當地語系化字串。
        /// </summary>
        internal static string IMGMenuBg {
            get {
                return ResourceManager.GetString("IMGMenuBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/menuIconBG.png 的當地語系化字串。
        /// </summary>
        internal static string IMGMenuIconBG {
            get {
                return ResourceManager.GetString("IMGMenuIconBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/menuIconBG2.png 的當地語系化字串。
        /// </summary>
        internal static string IMGMenuIconBG2 {
            get {
                return ResourceManager.GetString("IMGMenuIconBG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/menuIconBG3.png 的當地語系化字串。
        /// </summary>
        internal static string IMGMenuIconBG3 {
            get {
                return ResourceManager.GetString("IMGMenuIconBG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/menuIconBG3On.png 的當地語系化字串。
        /// </summary>
        internal static string IMGMenuIconBG3On {
            get {
                return ResourceManager.GetString("IMGMenuIconBG3On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/progressBar.png 的當地語系化字串。
        /// </summary>
        internal static string IMGProgressBar {
            get {
                return ResourceManager.GetString("IMGProgressBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/progressBarBg.png 的當地語系化字串。
        /// </summary>
        internal static string IMGProgressBarBg {
            get {
                return ResourceManager.GetString("IMGProgressBarBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/splashCenter.png 的當地語系化字串。
        /// </summary>
        internal static string IMGSplashCenter {
            get {
                return ResourceManager.GetString("IMGSplashCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/splashLeft.png 的當地語系化字串。
        /// </summary>
        internal static string IMGSplashLeft {
            get {
                return ResourceManager.GetString("IMGSplashLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/splashRight.png 的當地語系化字串。
        /// </summary>
        internal static string IMGSplashRight {
            get {
                return ResourceManager.GetString("IMGSplashRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/statusBg.png 的當地語系化字串。
        /// </summary>
        internal static string IMGStatusBg {
            get {
                return ResourceManager.GetString("IMGStatusBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/storageIcon.png 的當地語系化字串。
        /// </summary>
        internal static string IMGStorageIcon {
            get {
                return ResourceManager.GetString("IMGStorageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/timeIcon.png 的當地語系化字串。
        /// </summary>
        internal static string IMGTimeIcon {
            get {
                return ResourceManager.GetString("IMGTimeIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/toolBg.png 的當地語系化字串。
        /// </summary>
        internal static string IMGToolBg {
            get {
                return ResourceManager.GetString("IMGToolBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/toolBg2.png 的當地語系化字串。
        /// </summary>
        internal static string IMGToolBg2 {
            get {
                return ResourceManager.GetString("IMGToolBg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ./App/Resources/userIcon.png 的當地語系化字串。
        /// </summary>
        internal static string IMGUserIcon {
            get {
                return ResourceManager.GetString("IMGUserIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loading {
            get {
                object obj = ResourceManager.GetObject("loading", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loadingClock {
            get {
                object obj = ResourceManager.GetObject("loadingClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loginButton {
            get {
                object obj = ResourceManager.GetObject("loginButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loginPanel {
            get {
                object obj = ResourceManager.GetObject("loginPanel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap loginPanel2 {
            get {
                object obj = ResourceManager.GetObject("loginPanel2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap menuBg {
            get {
                object obj = ResourceManager.GetObject("menuBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap menuIconBG {
            get {
                object obj = ResourceManager.GetObject("menuIconBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap menuIconBG2 {
            get {
                object obj = ResourceManager.GetObject("menuIconBG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap menuIconBG3 {
            get {
                object obj = ResourceManager.GetObject("menuIconBG3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap menuIconBG3On {
            get {
                object obj = ResourceManager.GetObject("menuIconBG3On", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap progressBar {
            get {
                object obj = ResourceManager.GetObject("progressBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap progressBarBg {
            get {
                object obj = ResourceManager.GetObject("progressBarBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap setupMenuIcon {
            get {
                object obj = ResourceManager.GetObject("setupMenuIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap splashCenter {
            get {
                object obj = ResourceManager.GetObject("splashCenter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap splashLeft {
            get {
                object obj = ResourceManager.GetObject("splashLeft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap splashRight {
            get {
                object obj = ResourceManager.GetObject("splashRight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap statusBg {
            get {
                object obj = ResourceManager.GetObject("statusBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap storageIcon {
            get {
                object obj = ResourceManager.GetObject("storageIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap timeIcon {
            get {
                object obj = ResourceManager.GetObject("timeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap toolBg {
            get {
                object obj = ResourceManager.GetObject("toolBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap toolBg2 {
            get {
                object obj = ResourceManager.GetObject("toolBg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查詢類型 System.Drawing.Bitmap 的當地語系化資源。
        /// </summary>
        internal static System.Drawing.Bitmap userIcon {
            get {
                object obj = ResourceManager.GetObject("userIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
