//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTSReports.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTSReports.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap advancedSearchIcon {
            get {
                object obj = ResourceManager.GetObject("advancedSearchIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap advancedSearchIcon_activate {
            get {
                object obj = ResourceManager.GetObject("advancedSearchIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_noborder {
            get {
                object obj = ResourceManager.GetObject("bg_noborder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_click {
            get {
                object obj = ResourceManager.GetObject("button_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendarIcon {
            get {
                object obj = ResourceManager.GetObject("calendarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendarIcon_activate {
            get {
                object obj = ResourceManager.GetObject("calendarIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cashierIcon {
            get {
                object obj = ResourceManager.GetObject("cashierIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cashierIcon_activate {
            get {
                object obj = ResourceManager.GetObject("cashierIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deviationIcon {
            get {
                object obj = ResourceManager.GetObject("deviationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deviationIcon_activate {
            get {
                object obj = ResourceManager.GetObject("deviationIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap download {
            get {
                object obj = ResourceManager.GetObject("download", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exceptionIcon {
            get {
                object obj = ResourceManager.GetObject("exceptionIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exceptionIcon_activate {
            get {
                object obj = ResourceManager.GetObject("exceptionIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exceptionPercentageIcon {
            get {
                object obj = ResourceManager.GetObject("exceptionPercentageIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap exceptionPercentageIcon_activate {
            get {
                object obj = ResourceManager.GetObject("exceptionPercentageIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/advancedSearchIcon_activate.png.
        /// </summary>
        internal static string IMGAdvancedSearchActivate {
            get {
                return ResourceManager.GetString("IMGAdvancedSearchActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/advancedSearchIcon.png.
        /// </summary>
        internal static string IMGAdvancedSearchIcon {
            get {
                return ResourceManager.GetString("IMGAdvancedSearchIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/bg.png.
        /// </summary>
        internal static string IMGBg {
            get {
                return ResourceManager.GetString("IMGBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/bg_noborder.png.
        /// </summary>
        internal static string IMGBgNoborder {
            get {
                return ResourceManager.GetString("IMGBgNoborder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/calendarIcon.png.
        /// </summary>
        internal static string IMGCalendarIcon {
            get {
                return ResourceManager.GetString("IMGCalendarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/calendarIcon_activate.png.
        /// </summary>
        internal static string IMGCalendarIconActivate {
            get {
                return ResourceManager.GetString("IMGCalendarIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/cashierIcon.png.
        /// </summary>
        internal static string IMGCashierIcon {
            get {
                return ResourceManager.GetString("IMGCashierIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/cashierIcon_activate.png.
        /// </summary>
        internal static string IMGCashierIconActivate {
            get {
                return ResourceManager.GetString("IMGCashierIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/deviationIcon.png.
        /// </summary>
        internal static string IMGDeviationIcon {
            get {
                return ResourceManager.GetString("IMGDeviationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/deviationIcon_activate.png.
        /// </summary>
        internal static string IMGDeviationIconActivate {
            get {
                return ResourceManager.GetString("IMGDeviationIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/download.png.
        /// </summary>
        internal static string IMGDownload {
            get {
                return ResourceManager.GetString("IMGDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/exceptionIcon_activate.png.
        /// </summary>
        internal static string IMGExceptionActivate {
            get {
                return ResourceManager.GetString("IMGExceptionActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/exceptionIcon.png.
        /// </summary>
        internal static string IMGExceptionIcon {
            get {
                return ResourceManager.GetString("IMGExceptionIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/exceptionPercentageIcon.png.
        /// </summary>
        internal static string IMGExceptionPercentageIcon {
            get {
                return ResourceManager.GetString("IMGExceptionPercentageIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/exceptionPercentageIcon_activate.png.
        /// </summary>
        internal static string IMGExceptionPercentageIconActivate {
            get {
                return ResourceManager.GetString("IMGExceptionPercentageIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/image.png.
        /// </summary>
        internal static string IMGImage {
            get {
                return ResourceManager.GetString("IMGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/investigationIcon_activate.png.
        /// </summary>
        internal static string IMGInvestigationActivate {
            get {
                return ResourceManager.GetString("IMGInvestigationActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/investigationIcon.png.
        /// </summary>
        internal static string IMGInvestigationIcon {
            get {
                return ResourceManager.GetString("IMGInvestigationIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/next.png.
        /// </summary>
        internal static string IMGNext {
            get {
                return ResourceManager.GetString("IMGNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/no_image.png.
        /// </summary>
        internal static string IMGNo_image {
            get {
                return ResourceManager.GetString("IMGNo_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/previous.png.
        /// </summary>
        internal static string IMGPrevious {
            get {
                return ResourceManager.GetString("IMGPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/report.png.
        /// </summary>
        internal static string IMGReport {
            get {
                return ResourceManager.GetString("IMGReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/summaryIcon_activate.png.
        /// </summary>
        internal static string IMGSummaryActivate {
            get {
                return ResourceManager.GetString("IMGSummaryActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/summaryIcon.png.
        /// </summary>
        internal static string IMGSummaryIcon {
            get {
                return ResourceManager.GetString("IMGSummaryIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/templateIcon.png.
        /// </summary>
        internal static string IMGTemplateIcon {
            get {
                return ResourceManager.GetString("IMGTemplateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/templateIcon_activate.png.
        /// </summary>
        internal static string IMGTemplateIconActivate {
            get {
                return ResourceManager.GetString("IMGTemplateIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/thresholdIcon_activate.png.
        /// </summary>
        internal static string IMGThredholdActivate {
            get {
                return ResourceManager.GetString("IMGThredholdActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/thresholdIcon.png.
        /// </summary>
        internal static string IMGThredholdIcon {
            get {
                return ResourceManager.GetString("IMGThredholdIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/top2Icon.png.
        /// </summary>
        internal static string IMGTop2Icon {
            get {
                return ResourceManager.GetString("IMGTop2Icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/top2Icon_activate.png.
        /// </summary>
        internal static string IMGTop2IconActivate {
            get {
                return ResourceManager.GetString("IMGTop2IconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/trackingIcon.png.
        /// </summary>
        internal static string IMGTrackingIcon {
            get {
                return ResourceManager.GetString("IMGTrackingIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/trackingIcon_activate.png.
        /// </summary>
        internal static string IMGTrackingIconActivate {
            get {
                return ResourceManager.GetString("IMGTrackingIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/trendIcon.png.
        /// </summary>
        internal static string IMGTrendIcon {
            get {
                return ResourceManager.GetString("IMGTrendIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTSReports/Resources/trendIcon_activate.png.
        /// </summary>
        internal static string IMGTrendIconActivate {
            get {
                return ResourceManager.GetString("IMGTrendIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap investigationIcon {
            get {
                object obj = ResourceManager.GetObject("investigationIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap investigationIcon_activate {
            get {
                object obj = ResourceManager.GetObject("investigationIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_image {
            get {
                object obj = ResourceManager.GetObject("no_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap report {
            get {
                object obj = ResourceManager.GetObject("report", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap summaryIcon {
            get {
                object obj = ResourceManager.GetObject("summaryIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap summaryIcon_activate {
            get {
                object obj = ResourceManager.GetObject("summaryIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateIcon {
            get {
                object obj = ResourceManager.GetObject("templateIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap templateIcon_activate {
            get {
                object obj = ResourceManager.GetObject("templateIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thresholdIcon {
            get {
                object obj = ResourceManager.GetObject("thresholdIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap thresholdIcon_activate {
            get {
                object obj = ResourceManager.GetObject("thresholdIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top2Icon {
            get {
                object obj = ResourceManager.GetObject("top2Icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap top2Icon_activate {
            get {
                object obj = ResourceManager.GetObject("top2Icon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trackingIcon {
            get {
                object obj = ResourceManager.GetObject("trackingIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trackingIcon_activate {
            get {
                object obj = ResourceManager.GetObject("trackingIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trendIcon {
            get {
                object obj = ResourceManager.GetObject("trendIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trendIcon_activate {
            get {
                object obj = ResourceManager.GetObject("trendIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
