//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Investigation.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Investigation.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _do {
            get {
                object obj = ResourceManager.GetObject("_do", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audioDetection {
            get {
                object obj = ResourceManager.GetObject("audioDetection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audioDetection_on {
            get {
                object obj = ResourceManager.GetObject("audioDetection_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_click {
            get {
                object obj = ResourceManager.GetObject("button_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendarIcon {
            get {
                object obj = ResourceManager.GetObject("calendarIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap calendarIcon_activate {
            get {
                object obj = ResourceManager.GetObject("calendarIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crossline {
            get {
                object obj = ResourceManager.GetObject("crossline", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap crossline_on {
            get {
                object obj = ResourceManager.GetObject("crossline_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap di {
            get {
                object obj = ResourceManager.GetObject("di", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap di_on {
            get {
                object obj = ResourceManager.GetObject("di_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap do_on {
            get {
                object obj = ResourceManager.GetObject("do_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eventSearchIcon {
            get {
                object obj = ResourceManager.GetObject("eventSearchIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eventSearchIcon_activate {
            get {
                object obj = ResourceManager.GetObject("eventSearchIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap image {
            get {
                object obj = ResourceManager.GetObject("image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/audioDetection.png.
        /// </summary>
        internal static string IMGAudioDetection {
            get {
                return ResourceManager.GetString("IMGAudioDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/audioDetection_on.png.
        /// </summary>
        internal static string IMGAudioDetectionOn {
            get {
                return ResourceManager.GetString("IMGAudioDetectionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/calendarIcon.png.
        /// </summary>
        internal static string IMGCalendarIcon {
            get {
                return ResourceManager.GetString("IMGCalendarIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/calendarIcon_activate.png.
        /// </summary>
        internal static string IMGCalendarIconActivate {
            get {
                return ResourceManager.GetString("IMGCalendarIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Investigation/Resources/crossline.png.
        /// </summary>
        internal static string IMGCrossLine {
            get {
                return ResourceManager.GetString("IMGCrossLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Investigation/Resources/crossline_on.png.
        /// </summary>
        internal static string IMGCrossLineOn {
            get {
                return ResourceManager.GetString("IMGCrossLineOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/di.png.
        /// </summary>
        internal static string IMGDI {
            get {
                return ResourceManager.GetString("IMGDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/di_on.png.
        /// </summary>
        internal static string IMGDIOn {
            get {
                return ResourceManager.GetString("IMGDIOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/do.png.
        /// </summary>
        internal static string IMGDO {
            get {
                return ResourceManager.GetString("IMGDO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/do_on.png.
        /// </summary>
        internal static string IMGDOOn {
            get {
                return ResourceManager.GetString("IMGDOOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/eventSearchIcon.png.
        /// </summary>
        internal static string IMGEventSearchIcon {
            get {
                return ResourceManager.GetString("IMGEventSearchIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/eventSearchIcon_activate.png.
        /// </summary>
        internal static string IMGEventSearchIconActivate {
            get {
                return ResourceManager.GetString("IMGEventSearchIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/image.png.
        /// </summary>
        internal static string IMGImage {
            get {
                return ResourceManager.GetString("IMGImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/intrusionDetection.png.
        /// </summary>
        internal static string IMGIntrusionDetection {
            get {
                return ResourceManager.GetString("IMGIntrusionDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/intrusionDetection_on.png.
        /// </summary>
        internal static string IMGIntrusionDetectionOn {
            get {
                return ResourceManager.GetString("IMGIntrusionDetectionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/loiteringDetection.png.
        /// </summary>
        internal static string IMGLoiteringDetection {
            get {
                return ResourceManager.GetString("IMGLoiteringDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/loiteringDetection_on.png.
        /// </summary>
        internal static string IMGLoiteringDetectionOn {
            get {
                return ResourceManager.GetString("IMGLoiteringDetectionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/manualrecord.png.
        /// </summary>
        internal static string IMGManualRecord {
            get {
                return ResourceManager.GetString("IMGManualRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/manualrecord_on.png.
        /// </summary>
        internal static string IMGManualRecordOn {
            get {
                return ResourceManager.GetString("IMGManualRecordOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/motion.png.
        /// </summary>
        internal static string IMGMotion {
            get {
                return ResourceManager.GetString("IMGMotion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/motion_on.png.
        /// </summary>
        internal static string IMGMotionOn {
            get {
                return ResourceManager.GetString("IMGMotionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/networkloss.png.
        /// </summary>
        internal static string IMGNetworkLoss {
            get {
                return ResourceManager.GetString("IMGNetworkLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/networkloss_on.png.
        /// </summary>
        internal static string IMGNetworkLossOn {
            get {
                return ResourceManager.GetString("IMGNetworkLossOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/networkrecovery.png.
        /// </summary>
        internal static string IMGNetworkRecovery {
            get {
                return ResourceManager.GetString("IMGNetworkRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/networkrecovery_on.png.
        /// </summary>
        internal static string IMGNetworkRecoveryOn {
            get {
                return ResourceManager.GetString("IMGNetworkRecoveryOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/next.png.
        /// </summary>
        internal static string IMGNext {
            get {
                return ResourceManager.GetString("IMGNext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/no_image.png.
        /// </summary>
        internal static string IMGNo_image {
            get {
                return ResourceManager.GetString("IMGNo_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/objectCountingIn.png.
        /// </summary>
        internal static string IMGObjectCountingIn {
            get {
                return ResourceManager.GetString("IMGObjectCountingIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/objectCountingIn_on.png.
        /// </summary>
        internal static string IMGObjectCountingInOn {
            get {
                return ResourceManager.GetString("IMGObjectCountingInOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/objectCountingOut.png.
        /// </summary>
        internal static string IMGObjectCountingOut {
            get {
                return ResourceManager.GetString("IMGObjectCountingOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/objectCountingOut_on.png.
        /// </summary>
        internal static string IMGObjectCountingOutOn {
            get {
                return ResourceManager.GetString("IMGObjectCountingOutOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/panic.png.
        /// </summary>
        internal static string IMGPanic {
            get {
                return ResourceManager.GetString("IMGPanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/panic_on.png.
        /// </summary>
        internal static string IMGPanicOn {
            get {
                return ResourceManager.GetString("IMGPanicOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/previous.png.
        /// </summary>
        internal static string IMGPrevious {
            get {
                return ResourceManager.GetString("IMGPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/saveReport.png.
        /// </summary>
        internal static string IMGSaveReport {
            get {
                return ResourceManager.GetString("IMGSaveReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/smartSearchIcon.png.
        /// </summary>
        internal static string IMGSmartSearchIcon {
            get {
                return ResourceManager.GetString("IMGSmartSearchIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/smartSearchIcon_activate.png.
        /// </summary>
        internal static string IMGSmartSearchIconActivate {
            get {
                return ResourceManager.GetString("IMGSmartSearchIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/temperingDetection.png.
        /// </summary>
        internal static string IMGTemperingDetection {
            get {
                return ResourceManager.GetString("IMGTemperingDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/temperingDetection_on.png.
        /// </summary>
        internal static string IMGTemperingDetectionOn {
            get {
                return ResourceManager.GetString("IMGTemperingDetectionOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/userdefine.png.
        /// </summary>
        internal static string IMGUserdefined {
            get {
                return ResourceManager.GetString("IMGUserdefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/userdefine_on.png.
        /// </summary>
        internal static string IMGUserdefinedOn {
            get {
                return ResourceManager.GetString("IMGUserdefinedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/videoloss.png.
        /// </summary>
        internal static string IMGVideoLoss {
            get {
                return ResourceManager.GetString("IMGVideoLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/videoloss_on.png.
        /// </summary>
        internal static string IMGVideoLossOn {
            get {
                return ResourceManager.GetString("IMGVideoLossOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/videorecovery.png.
        /// </summary>
        internal static string IMGVideoRecovery {
            get {
                return ResourceManager.GetString("IMGVideoRecovery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Investigation/Resources/videorecovery_on.png.
        /// </summary>
        internal static string IMGVideoRecoveryOn {
            get {
                return ResourceManager.GetString("IMGVideoRecoveryOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap intrusionDetection {
            get {
                object obj = ResourceManager.GetObject("intrusionDetection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap intrusionDetection_on {
            get {
                object obj = ResourceManager.GetObject("intrusionDetection_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loiteringDetection {
            get {
                object obj = ResourceManager.GetObject("loiteringDetection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loiteringDetection_on {
            get {
                object obj = ResourceManager.GetObject("loiteringDetection_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manualrecord {
            get {
                object obj = ResourceManager.GetObject("manualrecord", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap manualrecord_on {
            get {
                object obj = ResourceManager.GetObject("manualrecord_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap motion {
            get {
                object obj = ResourceManager.GetObject("motion", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap motion_on {
            get {
                object obj = ResourceManager.GetObject("motion_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap networkloss {
            get {
                object obj = ResourceManager.GetObject("networkloss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap networkloss_on {
            get {
                object obj = ResourceManager.GetObject("networkloss_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap networkrecovery {
            get {
                object obj = ResourceManager.GetObject("networkrecovery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap networkrecovery_on {
            get {
                object obj = ResourceManager.GetObject("networkrecovery_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_image {
            get {
                object obj = ResourceManager.GetObject("no_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objectCountingIn {
            get {
                object obj = ResourceManager.GetObject("objectCountingIn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objectCountingIn_on {
            get {
                object obj = ResourceManager.GetObject("objectCountingIn_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objectCountingOut {
            get {
                object obj = ResourceManager.GetObject("objectCountingOut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap objectCountingOut_on {
            get {
                object obj = ResourceManager.GetObject("objectCountingOut_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap panic {
            get {
                object obj = ResourceManager.GetObject("panic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap panic_on {
            get {
                object obj = ResourceManager.GetObject("panic_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveReport {
            get {
                object obj = ResourceManager.GetObject("saveReport", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smartSearchIcon {
            get {
                object obj = ResourceManager.GetObject("smartSearchIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap smartSearchIcon_activate {
            get {
                object obj = ResourceManager.GetObject("smartSearchIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap temperingDetection {
            get {
                object obj = ResourceManager.GetObject("temperingDetection", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap temperingDetection_on {
            get {
                object obj = ResourceManager.GetObject("temperingDetection_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userdefine {
            get {
                object obj = ResourceManager.GetObject("userdefine", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap userdefine_on {
            get {
                object obj = ResourceManager.GetObject("userdefine_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap videoloss {
            get {
                object obj = ResourceManager.GetObject("videoloss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap videoloss_on {
            get {
                object obj = ResourceManager.GetObject("videoloss_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap videorecovery {
            get {
                object obj = ResourceManager.GetObject("videorecovery", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap videorecovery_on {
            get {
                object obj = ResourceManager.GetObject("videorecovery_on", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
