//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EMap.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EMap.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0 {
            get {
                object obj = ResourceManager.GetObject("_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0_activate {
            get {
                object obj = ResourceManager.GetObject("_0_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0_disconnect {
            get {
                object obj = ResourceManager.GetObject("_0_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _0_over {
            get {
                object obj = ResourceManager.GetObject("_0_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1 {
            get {
                object obj = ResourceManager.GetObject("_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_activate {
            get {
                object obj = ResourceManager.GetObject("_1_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_disconnect {
            get {
                object obj = ResourceManager.GetObject("_1_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _1_over {
            get {
                object obj = ResourceManager.GetObject("_1_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2 {
            get {
                object obj = ResourceManager.GetObject("_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_activate {
            get {
                object obj = ResourceManager.GetObject("_2_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_disconnect {
            get {
                object obj = ResourceManager.GetObject("_2_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _2_over {
            get {
                object obj = ResourceManager.GetObject("_2_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3 {
            get {
                object obj = ResourceManager.GetObject("_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_activate {
            get {
                object obj = ResourceManager.GetObject("_3_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_disconnect {
            get {
                object obj = ResourceManager.GetObject("_3_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _3_over {
            get {
                object obj = ResourceManager.GetObject("_3_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4 {
            get {
                object obj = ResourceManager.GetObject("_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_activate {
            get {
                object obj = ResourceManager.GetObject("_4_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_disconnect {
            get {
                object obj = ResourceManager.GetObject("_4_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4_over {
            get {
                object obj = ResourceManager.GetObject("_4_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5 {
            get {
                object obj = ResourceManager.GetObject("_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_activate {
            get {
                object obj = ResourceManager.GetObject("_5_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_disconnect {
            get {
                object obj = ResourceManager.GetObject("_5_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _5_over {
            get {
                object obj = ResourceManager.GetObject("_5_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6 {
            get {
                object obj = ResourceManager.GetObject("_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_activate {
            get {
                object obj = ResourceManager.GetObject("_6_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_disconnect {
            get {
                object obj = ResourceManager.GetObject("_6_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _6_over {
            get {
                object obj = ResourceManager.GetObject("_6_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7 {
            get {
                object obj = ResourceManager.GetObject("_7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_activate {
            get {
                object obj = ResourceManager.GetObject("_7_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_disconnect {
            get {
                object obj = ResourceManager.GetObject("_7_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _7_over {
            get {
                object obj = ResourceManager.GetObject("_7_over", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alarm {
            get {
                object obj = ResourceManager.GetObject("alarm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down_activate {
            get {
                object obj = ResourceManager.GetObject("arrow_down_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left {
            get {
                object obj = ResourceManager.GetObject("arrow_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_left_activate {
            get {
                object obj = ResourceManager.GetObject("arrow_left_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right {
            get {
                object obj = ResourceManager.GetObject("arrow_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_right_activate {
            get {
                object obj = ResourceManager.GetObject("arrow_right_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up_activate {
            get {
                object obj = ResourceManager.GetObject("arrow_up_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap audio {
            get {
                object obj = ResourceManager.GetObject("audio", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/banner.png.
        /// </summary>
        internal static string BGBanner {
            get {
                return ResourceManager.GetString("BGBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap button_click {
            get {
                object obj = ResourceManager.GetObject("button_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap buttonBG {
            get {
                object obj = ResourceManager.GetObject("buttonBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HotZone {
            get {
                object obj = ResourceManager.GetObject("HotZone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HotZoneActivate {
            get {
                object obj = ResourceManager.GetObject("HotZoneActivate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HotZoneGreyPoint {
            get {
                object obj = ResourceManager.GetObject("HotZoneGreyPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap HotZoneRedPoint {
            get {
                object obj = ResourceManager.GetObject("HotZoneRedPoint", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_transfer {
            get {
                object obj = ResourceManager.GetObject("icon_transfer", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_transfer_activate {
            get {
                object obj = ResourceManager.GetObject("icon_transfer_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/alarm.png.
        /// </summary>
        internal static string IMGAlarm {
            get {
                return ResourceManager.GetString("IMGAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_down.png.
        /// </summary>
        internal static string IMGArrowDown {
            get {
                return ResourceManager.GetString("IMGArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_down_activate.png.
        /// </summary>
        internal static string IMGArrowDownActivate {
            get {
                return ResourceManager.GetString("IMGArrowDownActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_left.png.
        /// </summary>
        internal static string IMGArrowLeft {
            get {
                return ResourceManager.GetString("IMGArrowLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_left_activate.png.
        /// </summary>
        internal static string IMGArrowLeftActivate {
            get {
                return ResourceManager.GetString("IMGArrowLeftActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_right.png.
        /// </summary>
        internal static string IMGArrowRight {
            get {
                return ResourceManager.GetString("IMGArrowRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_right_activate.png.
        /// </summary>
        internal static string IMGArrowRightActivate {
            get {
                return ResourceManager.GetString("IMGArrowRightActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_up.png.
        /// </summary>
        internal static string IMGArrowUp {
            get {
                return ResourceManager.GetString("IMGArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/arrow_up_activate.png.
        /// </summary>
        internal static string IMGArrowUpActivate {
            get {
                return ResourceManager.GetString("IMGArrowUpActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/audio.png.
        /// </summary>
        internal static string IMGAudio {
            get {
                return ResourceManager.GetString("IMGAudio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/button.png.
        /// </summary>
        internal static string IMGButton {
            get {
                return ResourceManager.GetString("IMGButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/cam.png.
        /// </summary>
        internal static string IMGCamera {
            get {
                return ResourceManager.GetString("IMGCamera", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/0.png.
        /// </summary>
        internal static string IMGCamera0 {
            get {
                return ResourceManager.GetString("IMGCamera0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/1.png.
        /// </summary>
        internal static string IMGCamera1 {
            get {
                return ResourceManager.GetString("IMGCamera1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/2.png.
        /// </summary>
        internal static string IMGCamera2 {
            get {
                return ResourceManager.GetString("IMGCamera2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/3.png.
        /// </summary>
        internal static string IMGCamera3 {
            get {
                return ResourceManager.GetString("IMGCamera3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/4.png.
        /// </summary>
        internal static string IMGCamera4 {
            get {
                return ResourceManager.GetString("IMGCamera4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/5.png.
        /// </summary>
        internal static string IMGCamera5 {
            get {
                return ResourceManager.GetString("IMGCamera5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/6.png.
        /// </summary>
        internal static string IMGCamera6 {
            get {
                return ResourceManager.GetString("IMGCamera6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/7.png.
        /// </summary>
        internal static string IMGCamera7 {
            get {
                return ResourceManager.GetString("IMGCamera7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/0_activate.png.
        /// </summary>
        internal static string IMGCameraActivate0 {
            get {
                return ResourceManager.GetString("IMGCameraActivate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/1_activate.png.
        /// </summary>
        internal static string IMGCameraActivate1 {
            get {
                return ResourceManager.GetString("IMGCameraActivate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/2_activate.png.
        /// </summary>
        internal static string IMGCameraActivate2 {
            get {
                return ResourceManager.GetString("IMGCameraActivate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/3_activate.png.
        /// </summary>
        internal static string IMGCameraActivate3 {
            get {
                return ResourceManager.GetString("IMGCameraActivate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/4_activate.png.
        /// </summary>
        internal static string IMGCameraActivate4 {
            get {
                return ResourceManager.GetString("IMGCameraActivate4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/5_activate.png.
        /// </summary>
        internal static string IMGCameraActivate5 {
            get {
                return ResourceManager.GetString("IMGCameraActivate5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/6_activate.png.
        /// </summary>
        internal static string IMGCameraActivate6 {
            get {
                return ResourceManager.GetString("IMGCameraActivate6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/7_activate.png.
        /// </summary>
        internal static string IMGCameraActivate7 {
            get {
                return ResourceManager.GetString("IMGCameraActivate7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/0_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect0 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/1_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect1 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/2_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect2 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/3_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect3 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/4_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect4 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/5_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect5 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/6_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect6 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/7_disconnect.png.
        /// </summary>
        internal static string IMGCameraDisconnect7 {
            get {
                return ResourceManager.GetString("IMGCameraDisconnect7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/0_over.png.
        /// </summary>
        internal static string IMGCameraOver0 {
            get {
                return ResourceManager.GetString("IMGCameraOver0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/1_over.png.
        /// </summary>
        internal static string IMGCameraOver1 {
            get {
                return ResourceManager.GetString("IMGCameraOver1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/2_over.png.
        /// </summary>
        internal static string IMGCameraOver2 {
            get {
                return ResourceManager.GetString("IMGCameraOver2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/3_over.png.
        /// </summary>
        internal static string IMGCameraOver3 {
            get {
                return ResourceManager.GetString("IMGCameraOver3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/4_over.png.
        /// </summary>
        internal static string IMGCameraOver4 {
            get {
                return ResourceManager.GetString("IMGCameraOver4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/5_over.png.
        /// </summary>
        internal static string IMGCameraOver5 {
            get {
                return ResourceManager.GetString("IMGCameraOver5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/6_over.png.
        /// </summary>
        internal static string IMGCameraOver6 {
            get {
                return ResourceManager.GetString("IMGCameraOver6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/7_over.png.
        /// </summary>
        internal static string IMGCameraOver7 {
            get {
                return ResourceManager.GetString("IMGCameraOver7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/windowClose.png.
        /// </summary>
        internal static string IMGCloseWindow {
            get {
                return ResourceManager.GetString("IMGCloseWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/hotZone.ico.
        /// </summary>
        internal static string IMGCursorHotZone {
            get {
                return ResourceManager.GetString("IMGCursorHotZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/ScreenDefault.png.
        /// </summary>
        internal static string IMGDefaultWindow {
            get {
                return ResourceManager.GetString("IMGDefaultWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/ScreenDefault_activate.png.
        /// </summary>
        internal static string IMGDefaultWindowActivate {
            get {
                return ResourceManager.GetString("IMGDefaultWindowActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/HotZone.png.
        /// </summary>
        internal static string IMGHotZone {
            get {
                return ResourceManager.GetString("IMGHotZone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/HotZoneActivate.png.
        /// </summary>
        internal static string IMGHotZoneActivate {
            get {
                return ResourceManager.GetString("IMGHotZoneActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/HotZoneGreyPoint.png.
        /// </summary>
        internal static string IMGHotZoneGreyPoint {
            get {
                return ResourceManager.GetString("IMGHotZoneGreyPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/HotZoneRedPoint.png.
        /// </summary>
        internal static string IMGHotZoneRedPoint {
            get {
                return ResourceManager.GetString("IMGHotZoneRedPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/large.png.
        /// </summary>
        internal static string IMGLargeWindow {
            get {
                return ResourceManager.GetString("IMGLargeWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/large_activate.png.
        /// </summary>
        internal static string IMGLargeWindowActivate {
            get {
                return ResourceManager.GetString("IMGLargeWindowActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/map.png.
        /// </summary>
        internal static string IMGMapIcon {
            get {
                return ResourceManager.GetString("IMGMapIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/map_activate.png.
        /// </summary>
        internal static string IMGMapIconActivate {
            get {
                return ResourceManager.GetString("IMGMapIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/medium.png.
        /// </summary>
        internal static string IMGMediumWindow {
            get {
                return ResourceManager.GetString("IMGMediumWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/medium_activate.png.
        /// </summary>
        internal static string IMGMediumWindowActivate {
            get {
                return ResourceManager.GetString("IMGMediumWindowActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/mini.png.
        /// </summary>
        internal static string IMGMini {
            get {
                return ResourceManager.GetString("IMGMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/mini2.png.
        /// </summary>
        internal static string IMGMini2 {
            get {
                return ResourceManager.GetString("IMGMini2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/modify.png.
        /// </summary>
        internal static string IMGModify {
            get {
                return ResourceManager.GetString("IMGModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/new.png.
        /// </summary>
        internal static string IMGNew {
            get {
                return ResourceManager.GetString("IMGNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/NVR.png.
        /// </summary>
        internal static string IMGNVR {
            get {
                return ResourceManager.GetString("IMGNVR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/NVR_activate.png.
        /// </summary>
        internal static string IMGNVRActivate {
            get {
                return ResourceManager.GetString("IMGNVRActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/NVR_disconnect.png.
        /// </summary>
        internal static string IMGNVRDisconnect {
            get {
                return ResourceManager.GetString("IMGNVRDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/original.png.
        /// </summary>
        internal static string IMGOriginalPoint {
            get {
                return ResourceManager.GetString("IMGOriginalPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/original_activate.png.
        /// </summary>
        internal static string IMGOriginalPointActivate {
            get {
                return ResourceManager.GetString("IMGOriginalPointActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/refresh.png.
        /// </summary>
        internal static string IMGRefresh {
            get {
                return ResourceManager.GetString("IMGRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/reload.png.
        /// </summary>
        internal static string IMGReload {
            get {
                return ResourceManager.GetString("IMGReload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/reset.png.
        /// </summary>
        internal static string IMGResetEvent {
            get {
                return ResourceManager.GetString("IMGResetEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/save.png.
        /// </summary>
        internal static string IMGSave {
            get {
                return ResourceManager.GetString("IMGSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/save_imageButton.png.
        /// </summary>
        internal static string IMGSaveButton {
            get {
                return ResourceManager.GetString("IMGSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/SelectFolder.png.
        /// </summary>
        internal static string IMGSelectFolder {
            get {
                return ResourceManager.GetString("IMGSelectFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/setup_map_activate.png.
        /// </summary>
        internal static string IMGSetupMapActivateIcon {
            get {
                return ResourceManager.GetString("IMGSetupMapActivateIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/setup_map.png.
        /// </summary>
        internal static string IMGSetupMapIcon {
            get {
                return ResourceManager.GetString("IMGSetupMapIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/small.png.
        /// </summary>
        internal static string IMGSmallWindow {
            get {
                return ResourceManager.GetString("IMGSmallWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/small_activate.png.
        /// </summary>
        internal static string IMGSmallWindowActivate {
            get {
                return ResourceManager.GetString("IMGSmallWindowActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/space.png.
        /// </summary>
        internal static string IMGSpace {
            get {
                return ResourceManager.GetString("IMGSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/speaker.png.
        /// </summary>
        internal static string IMGSpeaker {
            get {
                return ResourceManager.GetString("IMGSpeaker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/treeAlarm.png.
        /// </summary>
        internal static string IMGTreeAlarm {
            get {
                return ResourceManager.GetString("IMGTreeAlarm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/icon-transfer.png.
        /// </summary>
        internal static string IMGVia {
            get {
                return ResourceManager.GetString("IMGVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/icon-transfer-activate.png.
        /// </summary>
        internal static string IMGViaActivate {
            get {
                return ResourceManager.GetString("IMGViaActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/zoom1-1.png.
        /// </summary>
        internal static string IMGZoom1_1 {
            get {
                return ResourceManager.GetString("IMGZoom1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/zoom1-1_activate.png.
        /// </summary>
        internal static string IMGZoom1_1Activate {
            get {
                return ResourceManager.GetString("IMGZoom1_1Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/zoom_in.png.
        /// </summary>
        internal static string IMGZoomIn {
            get {
                return ResourceManager.GetString("IMGZoomIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/zoom_in_activate.png.
        /// </summary>
        internal static string IMGZoomInActivate {
            get {
                return ResourceManager.GetString("IMGZoomInActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/zoom_out.png.
        /// </summary>
        internal static string IMGZoomOut {
            get {
                return ResourceManager.GetString("IMGZoomOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/zoom_out_activate.png.
        /// </summary>
        internal static string IMGZoomOutActivate {
            get {
                return ResourceManager.GetString("IMGZoomOutActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap large {
            get {
                object obj = ResourceManager.GetObject("large", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap large_activate {
            get {
                object obj = ResourceManager.GetObject("large_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map {
            get {
                object obj = ResourceManager.GetObject("map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_activate {
            get {
                object obj = ResourceManager.GetObject("map_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap map_icon {
            get {
                object obj = ResourceManager.GetObject("map_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mapBG {
            get {
                object obj = ResourceManager.GetObject("mapBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medium {
            get {
                object obj = ResourceManager.GetObject("medium", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap medium_activate {
            get {
                object obj = ResourceManager.GetObject("medium_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini {
            get {
                object obj = ResourceManager.GetObject("mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini2 {
            get {
                object obj = ResourceManager.GetObject("mini2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap modify {
            get {
                object obj = ResourceManager.GetObject("modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NVR {
            get {
                object obj = ResourceManager.GetObject("NVR", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NVR_activate {
            get {
                object obj = ResourceManager.GetObject("NVR_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap NVR_disconnect {
            get {
                object obj = ResourceManager.GetObject("NVR_disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap original {
            get {
                object obj = ResourceManager.GetObject("original", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap original_activate {
            get {
                object obj = ResourceManager.GetObject("original_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 540.
        /// </summary>
        internal static string PadHeight {
            get {
                return ResourceManager.GetString("PadHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 720.
        /// </summary>
        internal static string PadWidth {
            get {
                return ResourceManager.GetString("PadWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reload {
            get {
                object obj = ResourceManager.GetObject("reload", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reset {
            get {
                object obj = ResourceManager.GetObject("reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap save_imageButton {
            get {
                object obj = ResourceManager.GetObject("save_imageButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./EMap/Resources/save_Button.png.
        /// </summary>
        internal static string SaveButton {
            get {
                return ResourceManager.GetString("SaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScreenDefault {
            get {
                object obj = ResourceManager.GetObject("ScreenDefault", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ScreenDefault_activate {
            get {
                object obj = ResourceManager.GetObject("ScreenDefault_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectColor {
            get {
                object obj = ResourceManager.GetObject("SelectColor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SelectFolder {
            get {
                object obj = ResourceManager.GetObject("SelectFolder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setup_map {
            get {
                object obj = ResourceManager.GetObject("setup_map", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap setup_map_activate {
            get {
                object obj = ResourceManager.GetObject("setup_map_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small {
            get {
                object obj = ResourceManager.GetObject("small", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap small_activate {
            get {
                object obj = ResourceManager.GetObject("small_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap space {
            get {
                object obj = ResourceManager.GetObject("space", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap speaker {
            get {
                object obj = ResourceManager.GetObject("speaker", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolBG {
            get {
                object obj = ResourceManager.GetObject("toolBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap treeAlarm {
            get {
                object obj = ResourceManager.GetObject("treeAlarm", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 330,330.
        /// </summary>
        internal static string VideoWindowSizeLarge {
            get {
                return ResourceManager.GetString("VideoWindowSizeLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 200,200.
        /// </summary>
        internal static string VideoWindowSizeMedium {
            get {
                return ResourceManager.GetString("VideoWindowSizeMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 120,120.
        /// </summary>
        internal static string VideoWindowSizeSmall {
            get {
                return ResourceManager.GetString("VideoWindowSizeSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap windowClose {
            get {
                object obj = ResourceManager.GetObject("windowClose", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_in {
            get {
                object obj = ResourceManager.GetObject("zoom_in", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_in_activate {
            get {
                object obj = ResourceManager.GetObject("zoom_in_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_out {
            get {
                object obj = ResourceManager.GetObject("zoom_out", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom_out_activate {
            get {
                object obj = ResourceManager.GetObject("zoom_out_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom1_1 {
            get {
                object obj = ResourceManager.GetObject("zoom1_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoom1_1_activate {
            get {
                object obj = ResourceManager.GetObject("zoom1_1_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
