//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/banner.png.
        /// </summary>
        internal static string IMGBanner {
            get {
                return ResourceManager.GetString("IMGBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_1.png.
        /// </summary>
        internal static string IMGLayout1 {
            get {
                return ResourceManager.GetString("IMGLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_10.png.
        /// </summary>
        internal static string IMGLayout10 {
            get {
                return ResourceManager.GetString("IMGLayout10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_10_use.png.
        /// </summary>
        internal static string IMGLayout10Use {
            get {
                return ResourceManager.GetString("IMGLayout10Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_16.png.
        /// </summary>
        internal static string IMGLayout16 {
            get {
                return ResourceManager.GetString("IMGLayout16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_16_use.png.
        /// </summary>
        internal static string IMGLayout16Use {
            get {
                return ResourceManager.GetString("IMGLayout16Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_1_use.png.
        /// </summary>
        internal static string IMGLayout1Use {
            get {
                return ResourceManager.GetString("IMGLayout1Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_2.png.
        /// </summary>
        internal static string IMGLayout2 {
            get {
                return ResourceManager.GetString("IMGLayout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_25.png.
        /// </summary>
        internal static string IMGLayout25 {
            get {
                return ResourceManager.GetString("IMGLayout25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_25_use.png.
        /// </summary>
        internal static string IMGLayout25Use {
            get {
                return ResourceManager.GetString("IMGLayout25Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_2a.png.
        /// </summary>
        internal static string IMGLayout2a {
            get {
                return ResourceManager.GetString("IMGLayout2a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_2a_use.png.
        /// </summary>
        internal static string IMGLayout2aUse {
            get {
                return ResourceManager.GetString("IMGLayout2aUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_2_use.png.
        /// </summary>
        internal static string IMGLayout2Use {
            get {
                return ResourceManager.GetString("IMGLayout2Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_3.png.
        /// </summary>
        internal static string IMGLayout3 {
            get {
                return ResourceManager.GetString("IMGLayout3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_36.png.
        /// </summary>
        internal static string IMGLayout36 {
            get {
                return ResourceManager.GetString("IMGLayout36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_36_use.png.
        /// </summary>
        internal static string IMGLayout36Use {
            get {
                return ResourceManager.GetString("IMGLayout36Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_3a.png.
        /// </summary>
        internal static string IMGLayout3a {
            get {
                return ResourceManager.GetString("IMGLayout3a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_3a_use.png.
        /// </summary>
        internal static string IMGLayout3aUse {
            get {
                return ResourceManager.GetString("IMGLayout3aUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_3_use.png.
        /// </summary>
        internal static string IMGLayout3Use {
            get {
                return ResourceManager.GetString("IMGLayout3Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_4.png.
        /// </summary>
        internal static string IMGLayout4 {
            get {
                return ResourceManager.GetString("IMGLayout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_49.png.
        /// </summary>
        internal static string IMGLayout49 {
            get {
                return ResourceManager.GetString("IMGLayout49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_49_use.png.
        /// </summary>
        internal static string IMGLayout49Use {
            get {
                return ResourceManager.GetString("IMGLayout49Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_4_use.png.
        /// </summary>
        internal static string IMGLayout4Use {
            get {
                return ResourceManager.GetString("IMGLayout4Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_5.png.
        /// </summary>
        internal static string IMGLayout5 {
            get {
                return ResourceManager.GetString("IMGLayout5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_5_use.png.
        /// </summary>
        internal static string IMGLayout5Use {
            get {
                return ResourceManager.GetString("IMGLayout5Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_6.png.
        /// </summary>
        internal static string IMGLayout6 {
            get {
                return ResourceManager.GetString("IMGLayout6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_64.png.
        /// </summary>
        internal static string IMGLayout64 {
            get {
                return ResourceManager.GetString("IMGLayout64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_64_use.png.
        /// </summary>
        internal static string IMGLayout64Use {
            get {
                return ResourceManager.GetString("IMGLayout64Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_6a.png.
        /// </summary>
        internal static string IMGLayout6a {
            get {
                return ResourceManager.GetString("IMGLayout6a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_6a_use.png.
        /// </summary>
        internal static string IMGLayout6aUse {
            get {
                return ResourceManager.GetString("IMGLayout6aUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_6_use.png.
        /// </summary>
        internal static string IMGLayout6Use {
            get {
                return ResourceManager.GetString("IMGLayout6Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_8.png.
        /// </summary>
        internal static string IMGLayout8 {
            get {
                return ResourceManager.GetString("IMGLayout8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_8a.png.
        /// </summary>
        internal static string IMGLayout8a {
            get {
                return ResourceManager.GetString("IMGLayout8a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_8a_use.png.
        /// </summary>
        internal static string IMGLayout8aUse {
            get {
                return ResourceManager.GetString("IMGLayout8aUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_8_use.png.
        /// </summary>
        internal static string IMGLayout8Use {
            get {
                return ResourceManager.GetString("IMGLayout8Use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_9.png.
        /// </summary>
        internal static string IMGLayout9 {
            get {
                return ResourceManager.GetString("IMGLayout9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_9a.png.
        /// </summary>
        internal static string IMGLayout9a {
            get {
                return ResourceManager.GetString("IMGLayout9a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_9a_use.png.
        /// </summary>
        internal static string IMGLayout9aUse {
            get {
                return ResourceManager.GetString("IMGLayout9aUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_9b.png.
        /// </summary>
        internal static string IMGLayout9b {
            get {
                return ResourceManager.GetString("IMGLayout9b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_9b_use.png.
        /// </summary>
        internal static string IMGLayout9bUse {
            get {
                return ResourceManager.GetString("IMGLayout9bUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./Pager/Resources/layout_9_use.png.
        /// </summary>
        internal static string IMGLayout9Use {
            get {
                return ResourceManager.GetString("IMGLayout9Use", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap layout_1 {
            get {
                object obj = ResourceManager.GetObject("layout_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_1_use {
            get {
                object obj = ResourceManager.GetObject("layout_1_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_10 {
            get {
                object obj = ResourceManager.GetObject("layout_10", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_10_use {
            get {
                object obj = ResourceManager.GetObject("layout_10_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_16 {
            get {
                object obj = ResourceManager.GetObject("layout_16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_16_use {
            get {
                object obj = ResourceManager.GetObject("layout_16_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2 {
            get {
                object obj = ResourceManager.GetObject("layout_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2_use {
            get {
                object obj = ResourceManager.GetObject("layout_2_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_25 {
            get {
                object obj = ResourceManager.GetObject("layout_25", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_25_use {
            get {
                object obj = ResourceManager.GetObject("layout_25_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2a {
            get {
                object obj = ResourceManager.GetObject("layout_2a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2a_use {
            get {
                object obj = ResourceManager.GetObject("layout_2a_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_3 {
            get {
                object obj = ResourceManager.GetObject("layout_3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_3_use {
            get {
                object obj = ResourceManager.GetObject("layout_3_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_36 {
            get {
                object obj = ResourceManager.GetObject("layout_36", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_36_use {
            get {
                object obj = ResourceManager.GetObject("layout_36_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_3a {
            get {
                object obj = ResourceManager.GetObject("layout_3a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_3a_use {
            get {
                object obj = ResourceManager.GetObject("layout_3a_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_4 {
            get {
                object obj = ResourceManager.GetObject("layout_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_4_use {
            get {
                object obj = ResourceManager.GetObject("layout_4_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_49 {
            get {
                object obj = ResourceManager.GetObject("layout_49", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_49_use {
            get {
                object obj = ResourceManager.GetObject("layout_49_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_5 {
            get {
                object obj = ResourceManager.GetObject("layout_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_5_use {
            get {
                object obj = ResourceManager.GetObject("layout_5_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_6 {
            get {
                object obj = ResourceManager.GetObject("layout_6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_6_use {
            get {
                object obj = ResourceManager.GetObject("layout_6_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_64 {
            get {
                object obj = ResourceManager.GetObject("layout_64", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_64_use {
            get {
                object obj = ResourceManager.GetObject("layout_64_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_6a {
            get {
                object obj = ResourceManager.GetObject("layout_6a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_6a_use {
            get {
                object obj = ResourceManager.GetObject("layout_6a_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_8 {
            get {
                object obj = ResourceManager.GetObject("layout_8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_8_use {
            get {
                object obj = ResourceManager.GetObject("layout_8_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_8a {
            get {
                object obj = ResourceManager.GetObject("layout_8a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_8a_use {
            get {
                object obj = ResourceManager.GetObject("layout_8a_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_9 {
            get {
                object obj = ResourceManager.GetObject("layout_9", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_9_use {
            get {
                object obj = ResourceManager.GetObject("layout_9_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_9a {
            get {
                object obj = ResourceManager.GetObject("layout_9a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_9a_use {
            get {
                object obj = ResourceManager.GetObject("layout_9a_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_9b {
            get {
                object obj = ResourceManager.GetObject("layout_9b", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_9b_use {
            get {
                object obj = ResourceManager.GetObject("layout_9b_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
