//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PanelBase.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PanelBase.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap activate {
            get {
                object obj = ResourceManager.GetObject("activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap banner2 {
            get {
                object obj = ResourceManager.GetObject("banner2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg {
            get {
                object obj = ResourceManager.GetObject("bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bg_noborder {
            get {
                object obj = ResourceManager.GetObject("bg_noborder", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse {
            get {
                object obj = ResourceManager.GetObject("collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap collapse2 {
            get {
                object obj = ResourceManager.GetObject("collapse2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap edit {
            get {
                object obj = ResourceManager.GetObject("edit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap expand {
            get {
                object obj = ResourceManager.GetObject("expand", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap firstPage {
            get {
                object obj = ResourceManager.GetObject("firstPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_bg_activate {
            get {
                object obj = ResourceManager.GetObject("icon_bg_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/activate.png.
        /// </summary>
        internal static string IMGActivate {
            get {
                return ResourceManager.GetString("IMGActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/banner.png.
        /// </summary>
        internal static string IMGBanner {
            get {
                return ResourceManager.GetString("IMGBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/banner2.png.
        /// </summary>
        internal static string IMGBanner2 {
            get {
                return ResourceManager.GetString("IMGBanner2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/bg.png.
        /// </summary>
        internal static string IMGBg {
            get {
                return ResourceManager.GetString("IMGBg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/bg_noborder.png.
        /// </summary>
        internal static string IMGBgNoborder {
            get {
                return ResourceManager.GetString("IMGBgNoborder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/b_border.png.
        /// </summary>
        internal static string IMGBottomBorder {
            get {
                return ResourceManager.GetString("IMGBottomBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/bl_round.png.
        /// </summary>
        internal static string IMGBottomLeftRound {
            get {
                return ResourceManager.GetString("IMGBottomLeftRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/br_round.png.
        /// </summary>
        internal static string IMGBottomRightRound {
            get {
                return ResourceManager.GetString("IMGBottomRightRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/collapse.png.
        /// </summary>
        internal static string IMGCollapse {
            get {
                return ResourceManager.GetString("IMGCollapse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/collapse2.png.
        /// </summary>
        internal static string IMGCollapse2 {
            get {
                return ResourceManager.GetString("IMGCollapse2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/edit.png.
        /// </summary>
        internal static string IMGEdit {
            get {
                return ResourceManager.GetString("IMGEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/expand.png.
        /// </summary>
        internal static string IMGExpand {
            get {
                return ResourceManager.GetString("IMGExpand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/firstPage.png.
        /// </summary>
        internal static string IMGFirstPage {
            get {
                return ResourceManager.GetString("IMGFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/icon_bg_activate.png.
        /// </summary>
        internal static string IMGIconBGActivate {
            get {
                return ResourceManager.GetString("IMGIconBGActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/inputBG_highlight.png.
        /// </summary>
        internal static string IMGInputBgHighlight {
            get {
                return ResourceManager.GetString("IMGInputBgHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/inputBG_title.png.
        /// </summary>
        internal static string IMGInputBgTitle {
            get {
                return ResourceManager.GetString("IMGInputBgTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_b_border.png.
        /// </summary>
        internal static string IMGInputBottomBorder {
            get {
                return ResourceManager.GetString("IMGInputBottomBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_bl_round.png.
        /// </summary>
        internal static string IMGInputBottomLeftRound {
            get {
                return ResourceManager.GetString("IMGInputBottomLeftRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_br_round.png.
        /// </summary>
        internal static string IMGInputBottomRightRound {
            get {
                return ResourceManager.GetString("IMGInputBottomRightRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_l_border.png.
        /// </summary>
        internal static string IMGInputLeftBorder {
            get {
                return ResourceManager.GetString("IMGInputLeftBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_left_highlight.png.
        /// </summary>
        internal static string IMGInputLeftHighlight {
            get {
                return ResourceManager.GetString("IMGInputLeftHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_left_split.png.
        /// </summary>
        internal static string IMGInputLeftSplit {
            get {
                return ResourceManager.GetString("IMGInputLeftSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_r_border.png.
        /// </summary>
        internal static string IMGInputRightBorder {
            get {
                return ResourceManager.GetString("IMGInputRightBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_right_highlight.png.
        /// </summary>
        internal static string IMGInputRightHighlight {
            get {
                return ResourceManager.GetString("IMGInputRightHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_right_split.png.
        /// </summary>
        internal static string IMGInputRightSplit {
            get {
                return ResourceManager.GetString("IMGInputRightSplit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_t_border.png.
        /// </summary>
        internal static string IMGInputTopBorder {
            get {
                return ResourceManager.GetString("IMGInputTopBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_tl_round.png.
        /// </summary>
        internal static string IMGInputTopLeftRound {
            get {
                return ResourceManager.GetString("IMGInputTopLeftRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/input_tr_round.png.
        /// </summary>
        internal static string IMGInputTopRightRound {
            get {
                return ResourceManager.GetString("IMGInputTopRightRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/keepSpaceBar.png.
        /// </summary>
        internal static string IMGKeepSpaceBar {
            get {
                return ResourceManager.GetString("IMGKeepSpaceBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/lastPage.png.
        /// </summary>
        internal static string IMGLastPage {
            get {
                return ResourceManager.GetString("IMGLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/l_border.png.
        /// </summary>
        internal static string IMGLeftBorder {
            get {
                return ResourceManager.GetString("IMGLeftBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./App/Resources/loadingClock.png.
        /// </summary>
        internal static string IMGLoadingClock {
            get {
                return ResourceManager.GetString("IMGLoadingClock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/mini.png.
        /// </summary>
        internal static string IMGMini {
            get {
                return ResourceManager.GetString("IMGMini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/mini2.png.
        /// </summary>
        internal static string IMGMini2 {
            get {
                return ResourceManager.GetString("IMGMini2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/modify.png.
        /// </summary>
        internal static string IMGModify {
            get {
                return ResourceManager.GetString("IMGModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/new.png.
        /// </summary>
        internal static string IMGNew {
            get {
                return ResourceManager.GetString("IMGNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/nextPage.png.
        /// </summary>
        internal static string IMGNextPage {
            get {
                return ResourceManager.GetString("IMGNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/previousPage.png.
        /// </summary>
        internal static string IMGPreviousPage {
            get {
                return ResourceManager.GetString("IMGPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/r_border.png.
        /// </summary>
        internal static string IMGRightBorder {
            get {
                return ResourceManager.GetString("IMGRightBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/selected.png.
        /// </summary>
        internal static string IMGSelected {
            get {
                return ResourceManager.GetString("IMGSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/storageBar.png.
        /// </summary>
        internal static string IMGStorageBar {
            get {
                return ResourceManager.GetString("IMGStorageBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/storageBar_activate.png.
        /// </summary>
        internal static string IMGStorageBar_activate {
            get {
                return ResourceManager.GetString("IMGStorageBar_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/storageBG.png.
        /// </summary>
        internal static string IMGStorageBG {
            get {
                return ResourceManager.GetString("IMGStorageBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/storageBG2.png.
        /// </summary>
        internal static string IMGStorageBG2 {
            get {
                return ResourceManager.GetString("IMGStorageBG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/titleBarBG.png.
        /// </summary>
        internal static string IMGTitleBarBG {
            get {
                return ResourceManager.GetString("IMGTitleBarBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/toolList.png.
        /// </summary>
        internal static string IMGToolList {
            get {
                return ResourceManager.GetString("IMGToolList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/t_border.png.
        /// </summary>
        internal static string IMGTopBorder {
            get {
                return ResourceManager.GetString("IMGTopBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/tl_round.png.
        /// </summary>
        internal static string IMGTopLeftRound {
            get {
                return ResourceManager.GetString("IMGTopLeftRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/tr_round.png.
        /// </summary>
        internal static string IMGTopRightRound {
            get {
                return ResourceManager.GetString("IMGTopRightRound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/tz_top_left_highlight.png.
        /// </summary>
        internal static string IMGTzTopLeftHighlight {
            get {
                return ResourceManager.GetString("IMGTzTopLeftHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/tz_top_left_title.png.
        /// </summary>
        internal static string IMGTzTopLeftTitle {
            get {
                return ResourceManager.GetString("IMGTzTopLeftTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/tz_top_right_highlight.png.
        /// </summary>
        internal static string IMGTzTopRightHighlight {
            get {
                return ResourceManager.GetString("IMGTzTopRightHighlight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/tz_top_right_title.png.
        /// </summary>
        internal static string IMGTzTopRightTitle {
            get {
                return ResourceManager.GetString("IMGTzTopRightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/ui2_mini.png.
        /// </summary>
        internal static string IMGUI2Mini {
            get {
                return ResourceManager.GetString("IMGUI2Mini", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/ui2_mini2.png.
        /// </summary>
        internal static string IMGUI2Mini2 {
            get {
                return ResourceManager.GetString("IMGUI2Mini2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PanelBase/Resources/unavailable.png.
        /// </summary>
        internal static string IMGUnavailable {
            get {
                return ResourceManager.GetString("IMGUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_b_border {
            get {
                object obj = ResourceManager.GetObject("input_b_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_bl_round {
            get {
                object obj = ResourceManager.GetObject("input_bl_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_br_round {
            get {
                object obj = ResourceManager.GetObject("input_br_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_l_border {
            get {
                object obj = ResourceManager.GetObject("input_l_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_left_highlight {
            get {
                object obj = ResourceManager.GetObject("input_left_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_left_split {
            get {
                object obj = ResourceManager.GetObject("input_left_split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_r_border {
            get {
                object obj = ResourceManager.GetObject("input_r_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_right_highlight {
            get {
                object obj = ResourceManager.GetObject("input_right_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_right_split {
            get {
                object obj = ResourceManager.GetObject("input_right_split", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_t_border {
            get {
                object obj = ResourceManager.GetObject("input_t_border", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_tl_round {
            get {
                object obj = ResourceManager.GetObject("input_tl_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap input_tr_round {
            get {
                object obj = ResourceManager.GetObject("input_tr_round", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inputBG_highlight {
            get {
                object obj = ResourceManager.GetObject("inputBG_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inputBG_title {
            get {
                object obj = ResourceManager.GetObject("inputBG_title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap keepSpaceBar {
            get {
                object obj = ResourceManager.GetObject("keepSpaceBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lastPage {
            get {
                object obj = ResourceManager.GetObject("lastPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap loadingClock {
            get {
                object obj = ResourceManager.GetObject("loadingClock", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini {
            get {
                object obj = ResourceManager.GetObject("mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap mini2 {
            get {
                object obj = ResourceManager.GetObject("mini2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap modify {
            get {
                object obj = ResourceManager.GetObject("modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nextPage {
            get {
                object obj = ResourceManager.GetObject("nextPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previousPage {
            get {
                object obj = ResourceManager.GetObject("previousPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap progressBar {
            get {
                object obj = ResourceManager.GetObject("progressBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap progressBarBg {
            get {
                object obj = ResourceManager.GetObject("progressBarBg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap selected {
            get {
                object obj = ResourceManager.GetObject("selected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storageBar {
            get {
                object obj = ResourceManager.GetObject("storageBar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storageBar_activate {
            get {
                object obj = ResourceManager.GetObject("storageBar_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storageBG {
            get {
                object obj = ResourceManager.GetObject("storageBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap storageBG2 {
            get {
                object obj = ResourceManager.GetObject("storageBG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap titleBarBG {
            get {
                object obj = ResourceManager.GetObject("titleBarBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolList {
            get {
                object obj = ResourceManager.GetObject("toolList", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tz_top_left_highlight {
            get {
                object obj = ResourceManager.GetObject("tz_top_left_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tz_top_left_title {
            get {
                object obj = ResourceManager.GetObject("tz_top_left_title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tz_top_right_highlight {
            get {
                object obj = ResourceManager.GetObject("tz_top_right_highlight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tz_top_right_title {
            get {
                object obj = ResourceManager.GetObject("tz_top_right_title", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui2_mini {
            get {
                object obj = ResourceManager.GetObject("ui2_mini", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ui2_mini2 {
            get {
                object obj = ResourceManager.GetObject("ui2_mini2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap unavailable {
            get {
                object obj = ResourceManager.GetObject("unavailable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
