//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetupServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetupServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk_err {
            get {
                object obj = ResourceManager.GetObject("disk_err", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk_lost {
            get {
                object obj = ResourceManager.GetObject("disk_lost", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk_rebuild {
            get {
                object obj = ResourceManager.GetObject("disk_rebuild", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk_run {
            get {
                object obj = ResourceManager.GetObject("disk_run", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk_stop {
            get {
                object obj = ResourceManager.GetObject("disk_stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disk_warning {
            get {
                object obj = ResourceManager.GetObject("disk_warning", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon_activate {
            get {
                object obj = ResourceManager.GetObject("icon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/disk_err.png.
        /// </summary>
        public static string IMGDiskError {
            get {
                return ResourceManager.GetString("IMGDiskError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/disk_lost.png.
        /// </summary>
        public static string IMGDiskLost {
            get {
                return ResourceManager.GetString("IMGDiskLost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/disk_rebuild.png.
        /// </summary>
        public static string IMGDiskRebuild {
            get {
                return ResourceManager.GetString("IMGDiskRebuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/disk_run.png.
        /// </summary>
        public static string IMGDiskRun {
            get {
                return ResourceManager.GetString("IMGDiskRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/disk_stop.png.
        /// </summary>
        public static string IMGDiskStop {
            get {
                return ResourceManager.GetString("IMGDiskStop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/disk_warning.png.
        /// </summary>
        public static string IMGDiskWarning {
            get {
                return ResourceManager.GetString("IMGDiskWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/icon.png.
        /// </summary>
        public static string IMGIcon {
            get {
                return ResourceManager.GetString("IMGIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupServer/Resources/icon_activate.png.
        /// </summary>
        public static string IMGIconActivate {
            get {
                return ResourceManager.GetString("IMGIconActivate", resourceCulture);
            }
        }
    }
}
