//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VideoMonitor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VideoMonitor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap audioin {
            get {
                object obj = ResourceManager.GetObject("audioin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap audioin_activate {
            get {
                object obj = ResourceManager.GetObject("audioin_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap audioin_disable {
            get {
                object obj = ResourceManager.GetObject("audioin_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap audioout {
            get {
                object obj = ResourceManager.GetObject("audioout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap audioout_activate {
            get {
                object obj = ResourceManager.GetObject("audioout_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap banner {
            get {
                object obj = ResourceManager.GetObject("banner", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/banner.png.
        /// </summary>
        public static string BGBanner {
            get {
                return ResourceManager.GetString("BGBanner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/controllerBG.png.
        /// </summary>
        public static string BGControllerBG {
            get {
                return ResourceManager.GetString("BGControllerBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/monitorBG.png.
        /// </summary>
        public static string BGMonitorBG {
            get {
                return ResourceManager.GetString("BGMonitorBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/viewerBG.png.
        /// </summary>
        public static string BGViewerBG {
            get {
                return ResourceManager.GetString("BGViewerBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap broadcast {
            get {
                object obj = ResourceManager.GetObject("broadcast", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap broadcast_activate {
            get {
                object obj = ResourceManager.GetObject("broadcast_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button {
            get {
                object obj = ResourceManager.GetObject("button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap button_click {
            get {
                object obj = ResourceManager.GetObject("button_click", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap cancelButotn {
            get {
                object obj = ResourceManager.GetObject("cancelButotn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap controllerBG {
            get {
                object obj = ResourceManager.GetObject("controllerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output1 {
            get {
                object obj = ResourceManager.GetObject("digital_output1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output1_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output1_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output2 {
            get {
                object obj = ResourceManager.GetObject("digital_output2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output2_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output2_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output3 {
            get {
                object obj = ResourceManager.GetObject("digital_output3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output3_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output3_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output4 {
            get {
                object obj = ResourceManager.GetObject("digital_output4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output4_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output4_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output5 {
            get {
                object obj = ResourceManager.GetObject("digital_output5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output5_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output5_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output6 {
            get {
                object obj = ResourceManager.GetObject("digital_output6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output6_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output6_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output7 {
            get {
                object obj = ResourceManager.GetObject("digital_output7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output7_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output7_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output8 {
            get {
                object obj = ResourceManager.GetObject("digital_output8", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap digital_output8_activate {
            get {
                object obj = ResourceManager.GetObject("digital_output8_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disconnect {
            get {
                object obj = ResourceManager.GetObject("disconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fisheye {
            get {
                object obj = ResourceManager.GetObject("fisheye", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fisheye_activate {
            get {
                object obj = ResourceManager.GetObject("fisheye_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fisheye_activate1 {
            get {
                object obj = ResourceManager.GetObject("fisheye_activate1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fisheye_activate2 {
            get {
                object obj = ResourceManager.GetObject("fisheye_activate2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap fisheye_activate3 {
            get {
                object obj = ResourceManager.GetObject("fisheye_activate3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/audioin.png.
        /// </summary>
        public static string IMGAudioin {
            get {
                return ResourceManager.GetString("IMGAudioin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/audioin_activate.png.
        /// </summary>
        public static string IMGAudioin_activate {
            get {
                return ResourceManager.GetString("IMGAudioin_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/audioin_disable.png.
        /// </summary>
        public static string IMGAudioin_disable {
            get {
                return ResourceManager.GetString("IMGAudioin_disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/audioout.png.
        /// </summary>
        public static string IMGAudioout {
            get {
                return ResourceManager.GetString("IMGAudioout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/audioout_activate.png.
        /// </summary>
        public static string IMGAudioout_activate {
            get {
                return ResourceManager.GetString("IMGAudioout_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/broadcast.png.
        /// </summary>
        public static string IMGBroadcast {
            get {
                return ResourceManager.GetString("IMGBroadcast", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/broadcast_activate.png.
        /// </summary>
        public static string IMGBroadcast_activate {
            get {
                return ResourceManager.GetString("IMGBroadcast_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/cancelButotn.png.
        /// </summary>
        public static string IMGCancelButotn {
            get {
                return ResourceManager.GetString("IMGCancelButotn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output1.png.
        /// </summary>
        public static string IMGDigital_output1 {
            get {
                return ResourceManager.GetString("IMGDigital_output1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output1_activate.png.
        /// </summary>
        public static string IMGDigital_output1_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output1_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output2.png.
        /// </summary>
        public static string IMGDigital_output2 {
            get {
                return ResourceManager.GetString("IMGDigital_output2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output2_activate.png.
        /// </summary>
        public static string IMGDigital_output2_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output2_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output3.png.
        /// </summary>
        public static string IMGDigital_output3 {
            get {
                return ResourceManager.GetString("IMGDigital_output3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output3_activate.png.
        /// </summary>
        public static string IMGDigital_output3_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output3_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output4.png.
        /// </summary>
        public static string IMGDigital_output4 {
            get {
                return ResourceManager.GetString("IMGDigital_output4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output4_activate.png.
        /// </summary>
        public static string IMGDigital_output4_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output4_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output5.png.
        /// </summary>
        public static string IMGDigital_output5 {
            get {
                return ResourceManager.GetString("IMGDigital_output5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output5_activate.png.
        /// </summary>
        public static string IMGDigital_output5_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output5_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output6.png.
        /// </summary>
        public static string IMGDigital_output6 {
            get {
                return ResourceManager.GetString("IMGDigital_output6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output6_activate.png.
        /// </summary>
        public static string IMGDigital_output6_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output6_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output7.png.
        /// </summary>
        public static string IMGDigital_output7 {
            get {
                return ResourceManager.GetString("IMGDigital_output7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output7_activate.png.
        /// </summary>
        public static string IMGDigital_output7_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output7_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output8.png.
        /// </summary>
        public static string IMGDigital_output8 {
            get {
                return ResourceManager.GetString("IMGDigital_output8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/digital_output8_activate.png.
        /// </summary>
        public static string IMGDigital_output8_activate {
            get {
                return ResourceManager.GetString("IMGDigital_output8_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/disconnect.png.
        /// </summary>
        public static string IMGDisconnect {
            get {
                return ResourceManager.GetString("IMGDisconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/fisheye.png.
        /// </summary>
        public static string IMGFisheye {
            get {
                return ResourceManager.GetString("IMGFisheye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/fisheye_activate.png.
        /// </summary>
        public static string IMGFisheye_activate {
            get {
                return ResourceManager.GetString("IMGFisheye_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/fisheye_activate1.png.
        /// </summary>
        public static string IMGFisheye_activate1 {
            get {
                return ResourceManager.GetString("IMGFisheye_activate1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/fisheye_activate2.png.
        /// </summary>
        public static string IMGFisheye_activate2 {
            get {
                return ResourceManager.GetString("IMGFisheye_activate2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/fisheye_activate3.png.
        /// </summary>
        public static string IMGFisheye_activate3 {
            get {
                return ResourceManager.GetString("IMGFisheye_activate3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/instantplayback.png.
        /// </summary>
        public static string IMGInstantplayback {
            get {
                return ResourceManager.GetString("IMGInstantplayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/instantplayback_activate.png.
        /// </summary>
        public static string IMGInstantplayback_activate {
            get {
                return ResourceManager.GetString("IMGInstantplayback_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/left.png.
        /// </summary>
        public static string IMGLeft {
            get {
                return ResourceManager.GetString("IMGLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/nextPage.png.
        /// </summary>
        public static string IMGNextPage {
            get {
                return ResourceManager.GetString("IMGNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/okButton.png.
        /// </summary>
        public static string IMGOKButton {
            get {
                return ResourceManager.GetString("IMGOKButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/opticalptz.png.
        /// </summary>
        public static string IMGOpticalptz {
            get {
                return ResourceManager.GetString("IMGOpticalptz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/opticalptz_activate.png.
        /// </summary>
        public static string IMGOpticalptz_activate {
            get {
                return ResourceManager.GetString("IMGOpticalptz_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/panic.png.
        /// </summary>
        public static string IMGPanic {
            get {
                return ResourceManager.GetString("IMGPanic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/panic_activate.png.
        /// </summary>
        public static string IMGPanic_activate {
            get {
                return ResourceManager.GetString("IMGPanic_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/playback.png.
        /// </summary>
        public static string IMGPlayback {
            get {
                return ResourceManager.GetString("IMGPlayback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/popup.png.
        /// </summary>
        public static string IMGPopup {
            get {
                return ResourceManager.GetString("IMGPopup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/previousPage.png.
        /// </summary>
        public static string IMGPreviousPage {
            get {
                return ResourceManager.GetString("IMGPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/reconnect.png.
        /// </summary>
        public static string IMGReconnect {
            get {
                return ResourceManager.GetString("IMGReconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/record.png.
        /// </summary>
        public static string IMGRecord {
            get {
                return ResourceManager.GetString("IMGRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/record_activate.png.
        /// </summary>
        public static string IMGRecord_activate {
            get {
                return ResourceManager.GetString("IMGRecord_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/recordButton.png.
        /// </summary>
        public static string IMGRecordButton {
            get {
                return ResourceManager.GetString("IMGRecordButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/right.png.
        /// </summary>
        public static string IMGRight {
            get {
                return ResourceManager.GetString("IMGRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/save_image.png.
        /// </summary>
        public static string IMGSave_image {
            get {
                return ResourceManager.GetString("IMGSave_image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/save_imageButton.png.
        /// </summary>
        public static string IMGSaveImageButton {
            get {
                return ResourceManager.GetString("IMGSaveImageButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/search.png.
        /// </summary>
        public static string IMGSearch {
            get {
                return ResourceManager.GetString("IMGSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/snapshot.png.
        /// </summary>
        public static string IMGSnapshot {
            get {
                return ResourceManager.GetString("IMGSnapshot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/save_imageButton.png.
        /// </summary>
        public static string IMGSnapshotButton {
            get {
                return ResourceManager.GetString("IMGSnapshotButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream1.png.
        /// </summary>
        public static string IMGStream1 {
            get {
                return ResourceManager.GetString("IMGStream1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream1_activate.png.
        /// </summary>
        public static string IMGStream1_activate {
            get {
                return ResourceManager.GetString("IMGStream1_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream2.png.
        /// </summary>
        public static string IMGStream2 {
            get {
                return ResourceManager.GetString("IMGStream2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream2_activate.png.
        /// </summary>
        public static string IMGStream2_activate {
            get {
                return ResourceManager.GetString("IMGStream2_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream3.png.
        /// </summary>
        public static string IMGStream3 {
            get {
                return ResourceManager.GetString("IMGStream3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream3_activate.png.
        /// </summary>
        public static string IMGStream3_activate {
            get {
                return ResourceManager.GetString("IMGStream3_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream4.png.
        /// </summary>
        public static string IMGStream4 {
            get {
                return ResourceManager.GetString("IMGStream4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream4_activate.png.
        /// </summary>
        public static string IMGStream4_activate {
            get {
                return ResourceManager.GetString("IMGStream4_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream5.png.
        /// </summary>
        public static string IMGStream5 {
            get {
                return ResourceManager.GetString("IMGStream5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream5_activate.png.
        /// </summary>
        public static string IMGStream5_activate {
            get {
                return ResourceManager.GetString("IMGStream5_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream6.png.
        /// </summary>
        public static string IMGStream6 {
            get {
                return ResourceManager.GetString("IMGStream6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stream6_activate.png.
        /// </summary>
        public static string IMGStream6_activate {
            get {
                return ResourceManager.GetString("IMGStream6_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stretch.png.
        /// </summary>
        public static string IMGStretch {
            get {
                return ResourceManager.GetString("IMGStretch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./VideoMonitor/Resources/stretch_activate.png.
        /// </summary>
        public static string IMGStretch_activate {
            get {
                return ResourceManager.GetString("IMGStretch_activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap instantplayback {
            get {
                object obj = ResourceManager.GetObject("instantplayback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap instantplayback_activate {
            get {
                object obj = ResourceManager.GetObject("instantplayback_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap left {
            get {
                object obj = ResourceManager.GetObject("left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap monitorBG {
            get {
                object obj = ResourceManager.GetObject("monitorBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap nextPage {
            get {
                object obj = ResourceManager.GetObject("nextPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap okButton {
            get {
                object obj = ResourceManager.GetObject("okButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap opticalptz {
            get {
                object obj = ResourceManager.GetObject("opticalptz", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap opticalptz_activate {
            get {
                object obj = ResourceManager.GetObject("opticalptz_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap panic {
            get {
                object obj = ResourceManager.GetObject("panic", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap panic_activate {
            get {
                object obj = ResourceManager.GetObject("panic_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap playback {
            get {
                object obj = ResourceManager.GetObject("playback", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap popup {
            get {
                object obj = ResourceManager.GetObject("popup", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap previousPage {
            get {
                object obj = ResourceManager.GetObject("previousPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reconnect {
            get {
                object obj = ResourceManager.GetObject("reconnect", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap record {
            get {
                object obj = ResourceManager.GetObject("record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap record_activate {
            get {
                object obj = ResourceManager.GetObject("record_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap recordButton {
            get {
                object obj = ResourceManager.GetObject("recordButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap right {
            get {
                object obj = ResourceManager.GetObject("right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_image {
            get {
                object obj = ResourceManager.GetObject("save_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap save_imageButton {
            get {
                object obj = ResourceManager.GetObject("save_imageButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search {
            get {
                object obj = ResourceManager.GetObject("search", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap snapshot {
            get {
                object obj = ResourceManager.GetObject("snapshot", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap snapshotButton {
            get {
                object obj = ResourceManager.GetObject("snapshotButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream1 {
            get {
                object obj = ResourceManager.GetObject("stream1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream1_activate {
            get {
                object obj = ResourceManager.GetObject("stream1_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream2 {
            get {
                object obj = ResourceManager.GetObject("stream2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream2_activate {
            get {
                object obj = ResourceManager.GetObject("stream2_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream3 {
            get {
                object obj = ResourceManager.GetObject("stream3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream3_activate {
            get {
                object obj = ResourceManager.GetObject("stream3_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream4 {
            get {
                object obj = ResourceManager.GetObject("stream4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream4_activate {
            get {
                object obj = ResourceManager.GetObject("stream4_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream5 {
            get {
                object obj = ResourceManager.GetObject("stream5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream5_activate {
            get {
                object obj = ResourceManager.GetObject("stream5_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream6 {
            get {
                object obj = ResourceManager.GetObject("stream6", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stream6_activate {
            get {
                object obj = ResourceManager.GetObject("stream6_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stretch {
            get {
                object obj = ResourceManager.GetObject("stretch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stretch_activate {
            get {
                object obj = ResourceManager.GetObject("stretch_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap toolBG {
            get {
                object obj = ResourceManager.GetObject("toolBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap viewerBG {
            get {
                object obj = ResourceManager.GetObject("viewerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
