//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetupSchedule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetupSchedule.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap alarm_icon {
            get {
                object obj = ResourceManager.GetObject("alarm_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/eraser_bg.png.
        /// </summary>
        internal static string BGEraser_bg {
            get {
                return ResourceManager.GetString("BGEraser_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/event_bg.png.
        /// </summary>
        internal static string BGEvent_bg {
            get {
                return ResourceManager.GetString("BGEvent_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/inputBG.png.
        /// </summary>
        internal static string BGInputBG {
            get {
                return ResourceManager.GetString("BGInputBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/inputBG_middle.png.
        /// </summary>
        internal static string BGInputBG_middle {
            get {
                return ResourceManager.GetString("BGInputBG_middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/record_bg.png.
        /// </summary>
        internal static string BGRecord_bg {
            get {
                return ResourceManager.GetString("BGRecord_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/sh_bottom_left.png.
        /// </summary>
        internal static string BGSh_bottom_left {
            get {
                return ResourceManager.GetString("BGSh_bottom_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/sh_bottom_right.png.
        /// </summary>
        internal static string BGSh_bottom_right {
            get {
                return ResourceManager.GetString("BGSh_bottom_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/sh_left.png.
        /// </summary>
        internal static string BGSh_left {
            get {
                return ResourceManager.GetString("BGSh_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/sh_right.png.
        /// </summary>
        internal static string BGSh_right {
            get {
                return ResourceManager.GetString("BGSh_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/sh_top_left.png.
        /// </summary>
        internal static string BGSh_top_left {
            get {
                return ResourceManager.GetString("BGSh_top_left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/sh_top_right.png.
        /// </summary>
        internal static string BGSh_top_right {
            get {
                return ResourceManager.GetString("BGSh_top_right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/tool_bg.png.
        /// </summary>
        internal static string BGTool_bg {
            get {
                return ResourceManager.GetString("BGTool_bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/tool_bg2.png.
        /// </summary>
        internal static string BGTool_bg2 {
            get {
                return ResourceManager.GetString("BGTool_bg2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser_bg {
            get {
                object obj = ResourceManager.GetObject("eraser_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap eraser_icon {
            get {
                object obj = ResourceManager.GetObject("eraser_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap event_bg {
            get {
                object obj = ResourceManager.GetObject("event_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap event_icon {
            get {
                object obj = ResourceManager.GetObject("event_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_activate {
            get {
                object obj = ResourceManager.GetObject("icon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/alarm_icon.png.
        /// </summary>
        internal static string IMGAlarm_icon {
            get {
                return ResourceManager.GetString("IMGAlarm_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/eraser_icon.png.
        /// </summary>
        internal static string IMGEraser_icon {
            get {
                return ResourceManager.GetString("IMGEraser_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/event_icon.png.
        /// </summary>
        internal static string IMGEvent_icon {
            get {
                return ResourceManager.GetString("IMGEvent_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/icon.png.
        /// </summary>
        internal static string IMGIcon {
            get {
                return ResourceManager.GetString("IMGIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/icon_activate.png.
        /// </summary>
        internal static string IMGIconActivate {
            get {
                return ResourceManager.GetString("IMGIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupSchedule/Resources/record_icon.png.
        /// </summary>
        internal static string IMGRecord_icon {
            get {
                return ResourceManager.GetString("IMGRecord_icon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inputBG {
            get {
                object obj = ResourceManager.GetObject("inputBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap inputBG_middle {
            get {
                object obj = ResourceManager.GetObject("inputBG_middle", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap record_bg {
            get {
                object obj = ResourceManager.GetObject("record_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap record_icon {
            get {
                object obj = ResourceManager.GetObject("record_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sh_bottom_left {
            get {
                object obj = ResourceManager.GetObject("sh_bottom_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sh_bottom_right {
            get {
                object obj = ResourceManager.GetObject("sh_bottom_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sh_left {
            get {
                object obj = ResourceManager.GetObject("sh_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sh_right {
            get {
                object obj = ResourceManager.GetObject("sh_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sh_top_left {
            get {
                object obj = ResourceManager.GetObject("sh_top_left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap sh_top_right {
            get {
                object obj = ResourceManager.GetObject("sh_top_right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tool_bg {
            get {
                object obj = ResourceManager.GetObject("tool_bg", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tool_bg2 {
            get {
                object obj = ResourceManager.GetObject("tool_bg2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
