//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SetupDeviceGroup.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SetupDeviceGroup.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap delete {
            get {
                object obj = ResourceManager.GetObject("delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap done {
            get {
                object obj = ResourceManager.GetObject("done", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_activate {
            get {
                object obj = ResourceManager.GetObject("icon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_layout {
            get {
                object obj = ResourceManager.GetObject("icon_layout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_layout_activate {
            get {
                object obj = ResourceManager.GetObject("icon_layout_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/delete.png.
        /// </summary>
        internal static string IMGDelete {
            get {
                return ResourceManager.GetString("IMGDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/done.png.
        /// </summary>
        internal static string IMGDone {
            get {
                return ResourceManager.GetString("IMGDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/icon.png.
        /// </summary>
        internal static string IMGIcon {
            get {
                return ResourceManager.GetString("IMGIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/icon_activate.png.
        /// </summary>
        internal static string IMGIconActivate {
            get {
                return ResourceManager.GetString("IMGIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/icon_layout.png.
        /// </summary>
        internal static string IMGIconLayout {
            get {
                return ResourceManager.GetString("IMGIconLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/icon_layout_activate.png.
        /// </summary>
        internal static string IMGIconLayoutActivate {
            get {
                return ResourceManager.GetString("IMGIconLayoutActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_1.png.
        /// </summary>
        internal static string IMGLayout1 {
            get {
                return ResourceManager.GetString("IMGLayout1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_1_use.png.
        /// </summary>
        internal static string IMGLayout1_use {
            get {
                return ResourceManager.GetString("IMGLayout1_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_1s.png.
        /// </summary>
        internal static string IMGLayout1WithSource {
            get {
                return ResourceManager.GetString("IMGLayout1WithSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_1s_use.png.
        /// </summary>
        internal static string IMGLayout1WithSource_use {
            get {
                return ResourceManager.GetString("IMGLayout1WithSource_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_2.png.
        /// </summary>
        internal static string IMGLayout2 {
            get {
                return ResourceManager.GetString("IMGLayout2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_2_use.png.
        /// </summary>
        internal static string IMGLayout2_use {
            get {
                return ResourceManager.GetString("IMGLayout2_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_2s.png.
        /// </summary>
        internal static string IMGLayout2WithSource {
            get {
                return ResourceManager.GetString("IMGLayout2WithSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_2s_use.png.
        /// </summary>
        internal static string IMGLayout2WithSource_use {
            get {
                return ResourceManager.GetString("IMGLayout2WithSource_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_4.png.
        /// </summary>
        internal static string IMGLayout4 {
            get {
                return ResourceManager.GetString("IMGLayout4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_4_use.png.
        /// </summary>
        internal static string IMGLayout4_use {
            get {
                return ResourceManager.GetString("IMGLayout4_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_4s.png.
        /// </summary>
        internal static string IMGLayout4WithSource {
            get {
                return ResourceManager.GetString("IMGLayout4WithSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/layout_4s_use.png.
        /// </summary>
        internal static string IMGLayout4WithSource_use {
            get {
                return ResourceManager.GetString("IMGLayout4WithSource_use", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./SetupDeviceGroup/Resources/set.png.
        /// </summary>
        internal static string IMGSet {
            get {
                return ResourceManager.GetString("IMGSet", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap layout_1 {
            get {
                object obj = ResourceManager.GetObject("layout_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_1_use {
            get {
                object obj = ResourceManager.GetObject("layout_1_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_1s {
            get {
                object obj = ResourceManager.GetObject("layout_1s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_1s_use {
            get {
                object obj = ResourceManager.GetObject("layout_1s_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2 {
            get {
                object obj = ResourceManager.GetObject("layout_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2_use {
            get {
                object obj = ResourceManager.GetObject("layout_2_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2s {
            get {
                object obj = ResourceManager.GetObject("layout_2s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_2s_use {
            get {
                object obj = ResourceManager.GetObject("layout_2s_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_4 {
            get {
                object obj = ResourceManager.GetObject("layout_4", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_4_use {
            get {
                object obj = ResourceManager.GetObject("layout_4_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_4s {
            get {
                object obj = ResourceManager.GetObject("layout_4s", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_4s_use {
            get {
                object obj = ResourceManager.GetObject("layout_4s_use", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap layout_5 {
            get {
                object obj = ResourceManager.GetObject("layout_5", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap set {
            get {
                object obj = ResourceManager.GetObject("set", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
