//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeviceTree.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DeviceTree.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _new {
            get {
                object obj = ResourceManager.GetObject("_new", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_down {
            get {
                object obj = ResourceManager.GetObject("arrow_down", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap arrow_up {
            get {
                object obj = ResourceManager.GetObject("arrow_up", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/controllerBG.png.
        /// </summary>
        internal static string BGControllerBG {
            get {
                return ResourceManager.GetString("BGControllerBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancelButotn {
            get {
                object obj = ResourceManager.GetObject("cancelButotn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap controllerBG {
            get {
                object obj = ResourceManager.GetObject("controllerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deviceListIcon {
            get {
                object obj = ResourceManager.GetObject("deviceListIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deviceListIcon_activate {
            get {
                object obj = ResourceManager.GetObject("deviceListIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap devicePanelBG {
            get {
                object obj = ResourceManager.GetObject("devicePanelBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deviceViewIcon {
            get {
                object obj = ResourceManager.GetObject("deviceViewIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deviceViewIcon_activate {
            get {
                object obj = ResourceManager.GetObject("deviceViewIcon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap failoverPanelBG {
            get {
                object obj = ResourceManager.GetObject("failoverPanelBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_closed {
            get {
                object obj = ResourceManager.GetObject("folder_closed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folder_open {
            get {
                object obj = ResourceManager.GetObject("folder_open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap folderPanelBG {
            get {
                object obj = ResourceManager.GetObject("folderPanelBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap gps_device {
            get {
                object obj = ResourceManager.GetObject("gps_device", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap group_state {
            get {
                object obj = ResourceManager.GetObject("group_state", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap group_state2 {
            get {
                object obj = ResourceManager.GetObject("group_state2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap groupPanelBG {
            get {
                object obj = ResourceManager.GetObject("groupPanelBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/arrow_down.png.
        /// </summary>
        internal static string IMGArrowDown {
            get {
                return ResourceManager.GetString("IMGArrowDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/arrow_up.png.
        /// </summary>
        internal static string IMGArrowUp {
            get {
                return ResourceManager.GetString("IMGArrowUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/cancelButotn.png.
        /// </summary>
        internal static string IMGCancelButotn {
            get {
                return ResourceManager.GetString("IMGCancelButotn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/deviceListIcon.png.
        /// </summary>
        internal static string IMGDeviceListIcon {
            get {
                return ResourceManager.GetString("IMGDeviceListIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/deviceListIcon_activate.png.
        /// </summary>
        internal static string IMGDeviceListIconActivate {
            get {
                return ResourceManager.GetString("IMGDeviceListIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/devicePanelBG.png.
        /// </summary>
        internal static string IMGDevicePanelBG {
            get {
                return ResourceManager.GetString("IMGDevicePanelBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/deviceViewIcon.png.
        /// </summary>
        internal static string IMGDeviceViewIcon {
            get {
                return ResourceManager.GetString("IMGDeviceViewIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/deviceViewIcon_activate.png.
        /// </summary>
        internal static string IMGDeviceViewIconActivate {
            get {
                return ResourceManager.GetString("IMGDeviceViewIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/failoverPanelBG.png.
        /// </summary>
        internal static string IMGFailoverPanelBG {
            get {
                return ResourceManager.GetString("IMGFailoverPanelBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/folder_closed.png.
        /// </summary>
        internal static string IMGFolderClosed {
            get {
                return ResourceManager.GetString("IMGFolderClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/folder_open.png.
        /// </summary>
        internal static string IMGFolderOpen {
            get {
                return ResourceManager.GetString("IMGFolderOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/folderPanelBG.png.
        /// </summary>
        internal static string IMGFolderPanelBG {
            get {
                return ResourceManager.GetString("IMGFolderPanelBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/groupPanelBG.png.
        /// </summary>
        internal static string IMGGroupPanelBG {
            get {
                return ResourceManager.GetString("IMGGroupPanelBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/group_state.png.
        /// </summary>
        internal static string IMGGroupState {
            get {
                return ResourceManager.GetString("IMGGroupState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/group_state2.png.
        /// </summary>
        internal static string IMGGroupState2 {
            get {
                return ResourceManager.GetString("IMGGroupState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/icon.png.
        /// </summary>
        internal static string IMGIcon {
            get {
                return ResourceManager.GetString("IMGIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/list.png.
        /// </summary>
        internal static string IMGList {
            get {
                return ResourceManager.GetString("IMGList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/list2.png.
        /// </summary>
        internal static string IMGList2 {
            get {
                return ResourceManager.GetString("IMGList2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/minus.png.
        /// </summary>
        internal static string IMGMinus {
            get {
                return ResourceManager.GetString("IMGMinus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/modify.png.
        /// </summary>
        internal static string IMGModify {
            get {
                return ResourceManager.GetString("IMGModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/new.png.
        /// </summary>
        internal static string IMGNew {
            get {
                return ResourceManager.GetString("IMGNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/normal.png.
        /// </summary>
        internal static string IMGNormal {
            get {
                return ResourceManager.GetString("IMGNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/nvr_state.png.
        /// </summary>
        internal static string IMGNvrState {
            get {
                return ResourceManager.GetString("IMGNvrState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/nvr_state2.png.
        /// </summary>
        internal static string IMGNvrState2 {
            get {
                return ResourceManager.GetString("IMGNvrState2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/online.png.
        /// </summary>
        internal static string IMGOnLine {
            get {
                return ResourceManager.GetString("IMGOnLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/patrol.png.
        /// </summary>
        internal static string IMGPatrol {
            get {
                return ResourceManager.GetString("IMGPatrol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/patrol_activate.png.
        /// </summary>
        internal static string IMGPatrolActivate {
            get {
                return ResourceManager.GetString("IMGPatrolActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/plus.png.
        /// </summary>
        internal static string IMGPlus {
            get {
                return ResourceManager.GetString("IMGPlus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/record.png.
        /// </summary>
        internal static string IMGRecord {
            get {
                return ResourceManager.GetString("IMGRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/saveButton.png.
        /// </summary>
        internal static string IMGSaveButton {
            get {
                return ResourceManager.GetString("IMGSaveButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./DeviceTree/Resources/yellow.png.
        /// </summary>
        internal static string IMGYellow {
            get {
                return ResourceManager.GetString("IMGYellow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list {
            get {
                object obj = ResourceManager.GetObject("list", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap list2 {
            get {
                object obj = ResourceManager.GetObject("list2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap modify {
            get {
                object obj = ResourceManager.GetObject("modify", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap normal {
            get {
                object obj = ResourceManager.GetObject("normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nvr_state {
            get {
                object obj = ResourceManager.GetObject("nvr_state", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nvr_state2 {
            get {
                object obj = ResourceManager.GetObject("nvr_state2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap online {
            get {
                object obj = ResourceManager.GetObject("online", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap patrol {
            get {
                object obj = ResourceManager.GetObject("patrol", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap patrol_activate {
            get {
                object obj = ResourceManager.GetObject("patrol_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plus {
            get {
                object obj = ResourceManager.GetObject("plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap record {
            get {
                object obj = ResourceManager.GetObject("record", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap saveButton {
            get {
                object obj = ResourceManager.GetObject("saveButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap yellow {
            get {
                object obj = ResourceManager.GetObject("yellow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
