//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1008
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PTZPanel.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PTZPanel.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap controllerBG {
            get {
                object obj = ResourceManager.GetObject("controllerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controllerBG2 {
            get {
                object obj = ResourceManager.GetObject("controllerBG2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap controllerLight {
            get {
                object obj = ResourceManager.GetObject("controllerLight", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap icon_activate {
            get {
                object obj = ResourceManager.GetObject("icon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/controllerBG.png.
        /// </summary>
        internal static string IMGControllerBG {
            get {
                return ResourceManager.GetString("IMGControllerBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/controllerBG2.png.
        /// </summary>
        internal static string IMGControllerBG2 {
            get {
                return ResourceManager.GetString("IMGControllerBG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/controllerLight.png.
        /// </summary>
        internal static string IMGControllerLight {
            get {
                return ResourceManager.GetString("IMGControllerLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/icon.png.
        /// </summary>
        internal static string IMGIcon {
            get {
                return ResourceManager.GetString("IMGIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/icon_activate.png.
        /// </summary>
        internal static string IMGIconActivate {
            get {
                return ResourceManager.GetString("IMGIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/incress.png.
        /// </summary>
        internal static string IMGIncress {
            get {
                return ResourceManager.GetString("IMGIncress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/incress_activate.png.
        /// </summary>
        internal static string IMGIncressActivate {
            get {
                return ResourceManager.GetString("IMGIncressActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/mover.png.
        /// </summary>
        internal static string IMGMover {
            get {
                return ResourceManager.GetString("IMGMover", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/mover_disable.png.
        /// </summary>
        internal static string IMGMoverDisable {
            get {
                return ResourceManager.GetString("IMGMoverDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/ptzBG.png.
        /// </summary>
        internal static string IMGPtzBG {
            get {
                return ResourceManager.GetString("IMGPtzBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/reduce.png.
        /// </summary>
        internal static string IMGReduce {
            get {
                return ResourceManager.GetString("IMGReduce", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/reduce_activate.png.
        /// </summary>
        internal static string IMGReduceActivate {
            get {
                return ResourceManager.GetString("IMGReduceActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PTZPanel/Resources/toolBG.png.
        /// </summary>
        internal static string IMGToolBG {
            get {
                return ResourceManager.GetString("IMGToolBG", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap incress {
            get {
                object obj = ResourceManager.GetObject("incress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap incress_activate {
            get {
                object obj = ResourceManager.GetObject("incress_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mover {
            get {
                object obj = ResourceManager.GetObject("mover", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap mover_disable {
            get {
                object obj = ResourceManager.GetObject("mover_disable", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ptzBG {
            get {
                object obj = ResourceManager.GetObject("ptzBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reduce {
            get {
                object obj = ResourceManager.GetObject("reduce", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap reduce_activate {
            get {
                object obj = ResourceManager.GetObject("reduce_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolBG {
            get {
                object obj = ResourceManager.GetObject("toolBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
