//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrintImageForm.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PrintImageForm.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap cancelButotn {
            get {
                object obj = ResourceManager.GetObject("cancelButotn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap controllerBG {
            get {
                object obj = ResourceManager.GetObject("controllerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PrintImageForm/Resources/cancelButotn.png.
        /// </summary>
        internal static string IMGCancelButotn {
            get {
                return ResourceManager.GetString("IMGCancelButotn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PrintImageForm/Resources/controllerBG.png.
        /// </summary>
        internal static string IMGControllerBG {
            get {
                return ResourceManager.GetString("IMGControllerBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PrintImageForm/Resources/nextPage.png.
        /// </summary>
        internal static string IMGNextPage {
            get {
                return ResourceManager.GetString("IMGNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PrintImageForm/Resources/no_image.png.
        /// </summary>
        internal static string IMGNoImage {
            get {
                return ResourceManager.GetString("IMGNoImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PrintImageForm/Resources/previousPage.png.
        /// </summary>
        internal static string IMGPreviousPage {
            get {
                return ResourceManager.GetString("IMGPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PrintImageForm/Resources/printButton.png.
        /// </summary>
        internal static string IMGPrintButton {
            get {
                return ResourceManager.GetString("IMGPrintButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./PrintImageForm/Resources/toolBG.png.
        /// </summary>
        internal static string IMGToolBG {
            get {
                return ResourceManager.GetString("IMGToolBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nextPage {
            get {
                object obj = ResourceManager.GetObject("nextPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap no_image {
            get {
                object obj = ResourceManager.GetObject("no_image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previousPage {
            get {
                object obj = ResourceManager.GetObject("previousPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap printButton {
            get {
                object obj = ResourceManager.GetObject("printButton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap toolBG {
            get {
                object obj = ResourceManager.GetObject("toolBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
