//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace POSException.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("POSException.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/controllerBG.png.
        /// </summary>
        internal static string BGControllerBG {
            get {
                return ResourceManager.GetString("BGControllerBG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap controllerBG {
            get {
                object obj = ResourceManager.GetObject("controllerBG", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap firstPage {
            get {
                object obj = ResourceManager.GetObject("firstPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap icon_activate {
            get {
                object obj = ResourceManager.GetObject("icon_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/firstPage.png.
        /// </summary>
        internal static string IMGFirstPage {
            get {
                return ResourceManager.GetString("IMGFirstPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/icon.png.
        /// </summary>
        internal static string IMGIcon {
            get {
                return ResourceManager.GetString("IMGIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/icon_activate.png.
        /// </summary>
        internal static string IMGIconActivate {
            get {
                return ResourceManager.GetString("IMGIconActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/lastPage.png.
        /// </summary>
        internal static string IMGLastPage {
            get {
                return ResourceManager.GetString("IMGLastPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/nextPage.png.
        /// </summary>
        internal static string IMGNextPage {
            get {
                return ResourceManager.GetString("IMGNextPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/pause_event.png.
        /// </summary>
        internal static string IMGPauseEvent {
            get {
                return ResourceManager.GetString("IMGPauseEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/pause_event_activate.png.
        /// </summary>
        internal static string IMGPauseEventActivate {
            get {
                return ResourceManager.GetString("IMGPauseEventActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/previousPage.png.
        /// </summary>
        internal static string IMGPreviousPage {
            get {
                return ResourceManager.GetString("IMGPreviousPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/refresh.png.
        /// </summary>
        internal static string IMGRefresh {
            get {
                return ResourceManager.GetString("IMGRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ./POSException/Resources/reset.png.
        /// </summary>
        internal static string IMGReset {
            get {
                return ResourceManager.GetString("IMGReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap lastPage {
            get {
                object obj = ResourceManager.GetObject("lastPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap nextPage {
            get {
                object obj = ResourceManager.GetObject("nextPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause_event {
            get {
                object obj = ResourceManager.GetObject("pause_event", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause_event_activate {
            get {
                object obj = ResourceManager.GetObject("pause_event_activate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previousPage {
            get {
                object obj = ResourceManager.GetObject("previousPage", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap refresh {
            get {
                object obj = ResourceManager.GetObject("refresh", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap reset {
            get {
                object obj = ResourceManager.GetObject("reset", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
